// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: credentials.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProjectCredential = `-- name: DeleteProjectCredential :execrows
DELETE FROM app.project_credentials WHERE project_id = $1 AND kind = $2
`

type DeleteProjectCredentialParams struct {
	ProjectID string
	Kind      string
}

func (q *Queries) DeleteProjectCredential(ctx context.Context, arg DeleteProjectCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectCredential, arg.ProjectID, arg.Kind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFencedJobProject = `-- name: GetFencedJobProject :one
SELECT project_id::text AS project_id
FROM app.jobs
WHERE id = $1::uuid AND runner_id = $2::uuid
  AND lease_generation = $3
  AND status IN ('preparing', 'running') AND lease_expires_at > now()
`

type GetFencedJobProjectParams struct {
	JobID           string
	RunnerID        string
	LeaseGeneration int64
}

func (q *Queries) GetFencedJobProject(ctx context.Context, arg GetFencedJobProjectParams) (string, error) {
	row := q.db.QueryRow(ctx, getFencedJobProject, arg.JobID, arg.RunnerID, arg.LeaseGeneration)
	var project_id string
	err := row.Scan(&project_id)
	return project_id, err
}

const getProjectCredentialSecret = `-- name: GetProjectCredentialSecret :one
SELECT ciphertext, nonce, file_path
FROM app.project_credentials
WHERE project_id = $1 AND kind = $2
`

type GetProjectCredentialSecretParams struct {
	ProjectID string
	Kind      string
}

type GetProjectCredentialSecretRow struct {
	Ciphertext []byte
	Nonce      []byte
	FilePath   string
}

func (q *Queries) GetProjectCredentialSecret(ctx context.Context, arg GetProjectCredentialSecretParams) (GetProjectCredentialSecretRow, error) {
	row := q.db.QueryRow(ctx, getProjectCredentialSecret, arg.ProjectID, arg.Kind)
	var i GetProjectCredentialSecretRow
	err := row.Scan(&i.Ciphertext, &i.Nonce, &i.FilePath)
	return i, err
}

const listProjectCredentials = `-- name: ListProjectCredentials :many
SELECT kind, created_at, updated_at, file_path
FROM app.project_credentials
WHERE project_id = $1
ORDER BY kind
`

type ListProjectCredentialsRow struct {
	Kind      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	FilePath  string
}

func (q *Queries) ListProjectCredentials(ctx context.Context, projectID string) ([]ListProjectCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listProjectCredentials, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectCredentialsRow
	for rows.Next() {
		var i ListProjectCredentialsRow
		if err := rows.Scan(
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FilePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectExists = `-- name: ProjectExists :one
SELECT EXISTS(SELECT 1 FROM app.projects WHERE id = $1) AS exists
`

func (q *Queries) ProjectExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, projectExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateProjectCredentialSecret = `-- name: UpdateProjectCredentialSecret :execrows
UPDATE app.project_credentials
SET ciphertext = $3, nonce = $4, updated_at = now()
WHERE project_id = $1 AND kind = $2
`

type UpdateProjectCredentialSecretParams struct {
	ProjectID  string
	Kind       string
	Ciphertext []byte
	Nonce      []byte
}

func (q *Queries) UpdateProjectCredentialSecret(ctx context.Context, arg UpdateProjectCredentialSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProjectCredentialSecret,
		arg.ProjectID,
		arg.Kind,
		arg.Ciphertext,
		arg.Nonce,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertProjectCredential = `-- name: UpsertProjectCredential :execrows
INSERT INTO app.project_credentials(project_id, kind, ciphertext, nonce, file_path)
SELECT $1, $2, $3, $4, $5
WHERE EXISTS (SELECT 1 FROM app.projects WHERE id = $1)
ON CONFLICT (project_id, kind) DO UPDATE SET
  ciphertext = EXCLUDED.ciphertext,
  nonce = EXCLUDED.nonce,
  file_path = EXCLUDED.file_path,
  updated_at = now()
`

type UpsertProjectCredentialParams struct {
	ProjectID  string
	Kind       string
	Ciphertext []byte
	Nonce      []byte
	FilePath   string
}

func (q *Queries) UpsertProjectCredential(ctx context.Context, arg UpsertProjectCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertProjectCredential,
		arg.ProjectID,
		arg.Kind,
		arg.Ciphertext,
		arg.Nonce,
		arg.FilePath,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
