// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: credentials.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProjectCredential = `-- name: DeleteProjectCredential :execrows
DELETE FROM app.project_credentials WHERE project_id = $1 AND kind = $2 AND task_source_id IS NULL
`

type DeleteProjectCredentialParams struct {
	ProjectID string
	Kind      string
}

func (q *Queries) DeleteProjectCredential(ctx context.Context, arg DeleteProjectCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectCredential, arg.ProjectID, arg.Kind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProjectCredentialForSource = `-- name: DeleteProjectCredentialForSource :execrows
DELETE FROM app.project_credentials WHERE project_id = $1 AND kind = $2 AND task_source_id = $3
`

type DeleteProjectCredentialForSourceParams struct {
	ProjectID    string
	Kind         string
	TaskSourceID pgtype.UUID
}

func (q *Queries) DeleteProjectCredentialForSource(ctx context.Context, arg DeleteProjectCredentialForSourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectCredentialForSource, arg.ProjectID, arg.Kind, arg.TaskSourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFencedJobProject = `-- name: GetFencedJobProject :one
SELECT project_id::text AS project_id
FROM app.jobs
WHERE id = $1::uuid AND runner_id = $2::uuid
  AND lease_generation = $3
  AND status IN ('preparing', 'running') AND lease_expires_at > now()
`

type GetFencedJobProjectParams struct {
	JobID           string
	RunnerID        string
	LeaseGeneration int64
}

func (q *Queries) GetFencedJobProject(ctx context.Context, arg GetFencedJobProjectParams) (string, error) {
	row := q.db.QueryRow(ctx, getFencedJobProject, arg.JobID, arg.RunnerID, arg.LeaseGeneration)
	var project_id string
	err := row.Scan(&project_id)
	return project_id, err
}

const getProjectCredentialSecret = `-- name: GetProjectCredentialSecret :one
SELECT ciphertext, nonce, file_path
FROM app.project_credentials
WHERE project_id = $1 AND kind = $2
  AND (task_source_id = NULLIF($3::text, '')::uuid OR task_source_id IS NULL)
ORDER BY (task_source_id IS NOT NULL) DESC
LIMIT 1
`

type GetProjectCredentialSecretParams struct {
	ProjectID    string
	Kind         string
	TaskSourceID string
}

type GetProjectCredentialSecretRow struct {
	Ciphertext []byte
	Nonce      []byte
	FilePath   string
}

// task_source_id (empty string = NULL, the same NULLIF convention CreateProject
// uses for repository_url) is the caller's scope: a CodeHost lookup always
// passes "" (a project has 0..1 code hosts, never per-source -- see
// #291/#293), so only a project-level row (task_source_id IS NULL) can ever
// match the OR's second arm for it, since the first arm compares against a
// NULL and can never be true. A TaskSource lookup passes its own source id
// and prefers a credential scoped to that source (the ORDER BY puts it
// first when both exist), falling back to the project-level one when the
// source has none of its own -- which is exactly what keeps an existing
// single-source project's credential (set before this migration,
// necessarily project-level) working unchanged after 026.
func (q *Queries) GetProjectCredentialSecret(ctx context.Context, arg GetProjectCredentialSecretParams) (GetProjectCredentialSecretRow, error) {
	row := q.db.QueryRow(ctx, getProjectCredentialSecret, arg.ProjectID, arg.Kind, arg.TaskSourceID)
	var i GetProjectCredentialSecretRow
	err := row.Scan(&i.Ciphertext, &i.Nonce, &i.FilePath)
	return i, err
}

const listProjectCredentials = `-- name: ListProjectCredentials :many
SELECT kind, created_at, updated_at, file_path, COALESCE(task_source_id::text, '') AS task_source_id
FROM app.project_credentials
WHERE project_id = $1
ORDER BY kind, task_source_id NULLS FIRST
`

type ListProjectCredentialsRow struct {
	Kind         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	FilePath     string
	TaskSourceID interface{}
}

// Lists every credential configured for the project, project-level and
// source-scoped alike; task_source_id (nullable) is what tells them apart.
// The gRPC surface (ListProjectCredentials/ProjectCredential) only ever
// writes project-level rows today, so in practice this is empty for every
// source-scoped row until a caller uses UpsertProjectCredentialForSource.
func (q *Queries) ListProjectCredentials(ctx context.Context, projectID string) ([]ListProjectCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listProjectCredentials, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectCredentialsRow
	for rows.Next() {
		var i ListProjectCredentialsRow
		if err := rows.Scan(
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FilePath,
			&i.TaskSourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectExists = `-- name: ProjectExists :one
SELECT EXISTS(SELECT 1 FROM app.projects WHERE id = $1) AS exists
`

func (q *Queries) ProjectExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, projectExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateProjectCredentialSecret = `-- name: UpdateProjectCredentialSecret :execrows
UPDATE app.project_credentials
SET ciphertext = $3, nonce = $4, updated_at = now()
WHERE project_id = $1 AND kind = $2 AND task_source_id IS NULL
`

type UpdateProjectCredentialSecretParams struct {
	ProjectID  string
	Kind       string
	Ciphertext []byte
	Nonce      []byte
}

func (q *Queries) UpdateProjectCredentialSecret(ctx context.Context, arg UpdateProjectCredentialSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProjectCredentialSecret,
		arg.ProjectID,
		arg.Kind,
		arg.Ciphertext,
		arg.Nonce,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertProjectCredential = `-- name: UpsertProjectCredential :execrows
INSERT INTO app.project_credentials(project_id, kind, ciphertext, nonce, file_path)
SELECT $1, $2, $3, $4, $5
WHERE EXISTS (SELECT 1 FROM app.projects WHERE id = $1)
ON CONFLICT (project_id, kind) WHERE task_source_id IS NULL DO UPDATE SET
  ciphertext = EXCLUDED.ciphertext,
  nonce = EXCLUDED.nonce,
  file_path = EXCLUDED.file_path,
  updated_at = now()
`

type UpsertProjectCredentialParams struct {
	ProjectID  string
	Kind       string
	Ciphertext []byte
	Nonce      []byte
	FilePath   string
}

// Project-level credential (task_source_id NULL): the only kind the API
// exposes today (SetProjectCredential/ClearProjectCredential/
// ListProjectCredentials never take a source id -- see #293's PR
// description). Targets the partial unique index migration 026 added for
// exactly this row shape.
func (q *Queries) UpsertProjectCredential(ctx context.Context, arg UpsertProjectCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertProjectCredential,
		arg.ProjectID,
		arg.Kind,
		arg.Ciphertext,
		arg.Nonce,
		arg.FilePath,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertProjectCredentialForSource = `-- name: UpsertProjectCredentialForSource :execrows
INSERT INTO app.project_credentials(project_id, kind, task_source_id, ciphertext, nonce, file_path)
SELECT $1, $2, $3, $4, $5, $6
WHERE EXISTS (SELECT 1 FROM app.projects WHERE id = $1)
ON CONFLICT (project_id, kind, task_source_id) WHERE task_source_id IS NOT NULL DO UPDATE SET
  ciphertext = EXCLUDED.ciphertext,
  nonce = EXCLUDED.nonce,
  file_path = EXCLUDED.file_path,
  updated_at = now()
`

type UpsertProjectCredentialForSourceParams struct {
	ProjectID    string
	Kind         string
	TaskSourceID pgtype.UUID
	Ciphertext   []byte
	Nonce        []byte
	FilePath     string
}

// Source-scoped credential (task_source_id set): what lets two task sources
// of the same provider each hold their own secret of a given kind, rather
// than colliding on the one project-level slot. Not wired to a gRPC RPC yet
// (see #293's PR description); exercised directly by
// TestProjectCredentialSourceScopingPreventsCollision to prove the schema
// decision actually holds.
func (q *Queries) UpsertProjectCredentialForSource(ctx context.Context, arg UpsertProjectCredentialForSourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertProjectCredentialForSource,
		arg.ProjectID,
		arg.Kind,
		arg.TaskSourceID,
		arg.Ciphertext,
		arg.Nonce,
		arg.FilePath,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
