// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: delivery.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProjectLock = `-- name: DeleteProjectLock :exec
DELETE FROM app.project_locks WHERE project_id = $1 AND workflow_run_id = $2
`

type DeleteProjectLockParams struct {
	ProjectID     string
	WorkflowRunID string
}

func (q *Queries) DeleteProjectLock(ctx context.Context, arg DeleteProjectLockParams) error {
	_, err := q.db.Exec(ctx, deleteProjectLock, arg.ProjectID, arg.WorkflowRunID)
	return err
}

const getDeliveryWorkflow = `-- name: GetDeliveryWorkflow :one
SELECT wr.project_id::text AS project_id, wr.issue_id::text AS issue_id, i.external_id, i.title, i.body,
       COALESCE(p.repository_url, '') AS repository_url, p.default_branch,
       COALESCE(wr.branch_name, '') AS branch_name, pr.external_id AS pr_external_id
FROM app.workflow_runs wr
JOIN app.issues i ON i.id = wr.issue_id
JOIN app.projects p ON p.id = wr.project_id
LEFT JOIN app.pull_requests pr ON pr.workflow_run_id = wr.id
WHERE wr.id = $1
`

type GetDeliveryWorkflowRow struct {
	ProjectID     string
	IssueID       string
	ExternalID    string
	Title         string
	Body          string
	RepositoryUrl string
	DefaultBranch string
	BranchName    string
	PrExternalID  pgtype.Text
}

func (q *Queries) GetDeliveryWorkflow(ctx context.Context, id string) (GetDeliveryWorkflowRow, error) {
	row := q.db.QueryRow(ctx, getDeliveryWorkflow, id)
	var i GetDeliveryWorkflowRow
	err := row.Scan(
		&i.ProjectID,
		&i.IssueID,
		&i.ExternalID,
		&i.Title,
		&i.Body,
		&i.RepositoryUrl,
		&i.DefaultBranch,
		&i.BranchName,
		&i.PrExternalID,
	)
	return i, err
}

const insertPullRequestCreatedEvent = `-- name: InsertPullRequestCreatedEvent :exec
INSERT INTO app.workflow_events(workflow_run_id, event_type, severity, payload)
VALUES ($1, 'pull_request.created', 'info', $2::jsonb)
`

type InsertPullRequestCreatedEventParams struct {
	WorkflowRunID string
	Payload       []byte
}

func (q *Queries) InsertPullRequestCreatedEvent(ctx context.Context, arg InsertPullRequestCreatedEventParams) error {
	_, err := q.db.Exec(ctx, insertPullRequestCreatedEvent, arg.WorkflowRunID, arg.Payload)
	return err
}

const insertPullRequestMergedEvent = `-- name: InsertPullRequestMergedEvent :exec
INSERT INTO app.workflow_events(workflow_run_id, event_type, severity, payload)
VALUES ($1, 'pull_request.merged', 'info', '{}'::jsonb)
`

func (q *Queries) InsertPullRequestMergedEvent(ctx context.Context, workflowRunID string) error {
	_, err := q.db.Exec(ctx, insertPullRequestMergedEvent, workflowRunID)
	return err
}

const insertWorkflowTerminationEvent = `-- name: InsertWorkflowTerminationEvent :exec
INSERT INTO app.workflow_events(workflow_run_id, event_type, severity, payload)
VALUES ($1, $2, 'error', $3::jsonb)
`

type InsertWorkflowTerminationEventParams struct {
	WorkflowRunID string
	EventType     string
	Payload       []byte
}

func (q *Queries) InsertWorkflowTerminationEvent(ctx context.Context, arg InsertWorkflowTerminationEventParams) error {
	_, err := q.db.Exec(ctx, insertWorkflowTerminationEvent, arg.WorkflowRunID, arg.EventType, arg.Payload)
	return err
}

const markIssueIneligible = `-- name: MarkIssueIneligible :exec
UPDATE app.issues SET eligible = false WHERE id = $1
`

func (q *Queries) MarkIssueIneligible(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markIssueIneligible, id)
	return err
}

const markPullRequestMerged = `-- name: MarkPullRequestMerged :exec
UPDATE app.pull_requests SET state = 'merged', merged_at = now() WHERE workflow_run_id = $1
`

func (q *Queries) MarkPullRequestMerged(ctx context.Context, workflowRunID string) error {
	_, err := q.db.Exec(ctx, markPullRequestMerged, workflowRunID)
	return err
}

const markWorkflowCompleted = `-- name: MarkWorkflowCompleted :execrows
UPDATE app.workflow_runs
SET status = 'completed', current_phase = 'completed', completed_at = now(), updated_at = now()
WHERE id = $1 AND status = 'waiting_github_checks'
`

func (q *Queries) MarkWorkflowCompleted(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, markWorkflowCompleted, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markWorkflowDelivered = `-- name: MarkWorkflowDelivered :execrows
UPDATE app.workflow_runs
SET status = 'waiting_github_checks', current_phase = 'waiting_github_checks', updated_at = now(), completed_at = NULL
WHERE id = $1 AND status = 'delivering'
`

func (q *Queries) MarkWorkflowDelivered(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, markWorkflowDelivered, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const selectWaitingGithubChecksWorkflows = `-- name: SelectWaitingGithubChecksWorkflows :many
SELECT wr.id::text AS id
FROM app.workflow_runs wr
WHERE wr.status = 'waiting_github_checks'
ORDER BY wr.updated_at, wr.id
LIMIT 20
`

func (q *Queries) SelectWaitingGithubChecksWorkflows(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, selectWaitingGithubChecksWorkflows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const terminateWorkflowRun = `-- name: TerminateWorkflowRun :one
UPDATE app.workflow_runs
SET status = $1, current_phase = $1,
    blocking_reason = $2, terminal_reason = $2,
    completed_at = now(), updated_at = now()
WHERE id = $3 AND status NOT IN ('failed', 'blocked', 'cancelled')
RETURNING project_id::text AS project_id
`

type TerminateWorkflowRunParams struct {
	Status string
	Reason pgtype.Text
	ID     string
}

func (q *Queries) TerminateWorkflowRun(ctx context.Context, arg TerminateWorkflowRunParams) (string, error) {
	row := q.db.QueryRow(ctx, terminateWorkflowRun, arg.Status, arg.Reason, arg.ID)
	var project_id string
	err := row.Scan(&project_id)
	return project_id, err
}

const upsertPullRequest = `-- name: UpsertPullRequest :exec
INSERT INTO app.pull_requests(id, workflow_run_id, provider, external_id, url, head_commit, state)
VALUES ($1, $2, 'github', $3, $4, $5, $6)
ON CONFLICT (workflow_run_id) DO UPDATE SET
  external_id = EXCLUDED.external_id,
  url = EXCLUDED.url,
  head_commit = EXCLUDED.head_commit,
  state = EXCLUDED.state
`

type UpsertPullRequestParams struct {
	ID            string
	WorkflowRunID string
	ExternalID    string
	Url           string
	HeadCommit    string
	State         string
}

func (q *Queries) UpsertPullRequest(ctx context.Context, arg UpsertPullRequestParams) error {
	_, err := q.db.Exec(ctx, upsertPullRequest,
		arg.ID,
		arg.WorkflowRunID,
		arg.ExternalID,
		arg.Url,
		arg.HeadCommit,
		arg.State,
	)
	return err
}
