// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: management.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRunnerRegistrationToken = `-- name: CreateRunnerRegistrationToken :one
INSERT INTO app.runner_registration_tokens(id, token_hash, created_by_user_id, allowed_labels, expires_at)
VALUES ($1, $2, $3::uuid, $4::jsonb, now() + interval '15 minutes')
RETURNING expires_at
`

type CreateRunnerRegistrationTokenParams struct {
	ID              string
	TokenHash       string
	CreatedByUserID string
	AllowedLabels   []byte
}

func (q *Queries) CreateRunnerRegistrationToken(ctx context.Context, arg CreateRunnerRegistrationTokenParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, createRunnerRegistrationToken,
		arg.ID,
		arg.TokenHash,
		arg.CreatedByUserID,
		arg.AllowedLabels,
	)
	var expires_at pgtype.Timestamptz
	err := row.Scan(&expires_at)
	return expires_at, err
}

const getSessionCSRFHash = `-- name: GetSessionCSRFHash :one
SELECT csrf_token_hash
FROM app.user_sessions
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) GetSessionCSRFHash(ctx context.Context, tokenHash string) (string, error) {
	row := q.db.QueryRow(ctx, getSessionCSRFHash, tokenHash)
	var csrf_token_hash string
	err := row.Scan(&csrf_token_hash)
	return csrf_token_hash, err
}

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT username, password_hash, email, display_name
FROM app.users
WHERE id = $1
FOR UPDATE
`

type GetUserForUpdateRow struct {
	Username     string
	PasswordHash string
	Email        string
	DisplayName  string
}

func (q *Queries) GetUserForUpdate(ctx context.Context, id string) (GetUserForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getUserForUpdate, id)
	var i GetUserForUpdateRow
	err := row.Scan(
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.DisplayName,
	)
	return i, err
}

const listRunnerRegistrationTokens = `-- name: ListRunnerRegistrationTokens :many
SELECT id::text AS id, allowed_labels::text AS allowed_labels, created_at, expires_at, used_at, revoked_at
FROM app.runner_registration_tokens
ORDER BY created_at DESC, id
`

type ListRunnerRegistrationTokensRow struct {
	ID            string
	AllowedLabels string
	CreatedAt     pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	UsedAt        pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
}

func (q *Queries) ListRunnerRegistrationTokens(ctx context.Context) ([]ListRunnerRegistrationTokensRow, error) {
	rows, err := q.db.Query(ctx, listRunnerRegistrationTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunnerRegistrationTokensRow
	for rows.Next() {
		var i ListRunnerRegistrationTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.AllowedLabels,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOtherUserSessions = `-- name: RevokeOtherUserSessions :exec
UPDATE app.user_sessions
SET revoked_at = now()
WHERE user_id = $1 AND token_hash <> $2 AND revoked_at IS NULL
`

type RevokeOtherUserSessionsParams struct {
	UserID    string
	TokenHash string
}

func (q *Queries) RevokeOtherUserSessions(ctx context.Context, arg RevokeOtherUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeOtherUserSessions, arg.UserID, arg.TokenHash)
	return err
}

const revokeRunnerRegistrationToken = `-- name: RevokeRunnerRegistrationToken :one
UPDATE app.runner_registration_tokens
SET revoked_at = COALESCE(revoked_at, now())
WHERE id = $1
RETURNING id::text AS id, allowed_labels::text AS allowed_labels, created_at, expires_at, used_at, revoked_at
`

type RevokeRunnerRegistrationTokenRow struct {
	ID            string
	AllowedLabels string
	CreatedAt     pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	UsedAt        pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
}

func (q *Queries) RevokeRunnerRegistrationToken(ctx context.Context, id string) (RevokeRunnerRegistrationTokenRow, error) {
	row := q.db.QueryRow(ctx, revokeRunnerRegistrationToken, id)
	var i RevokeRunnerRegistrationTokenRow
	err := row.Scan(
		&i.ID,
		&i.AllowedLabels,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE app.users
SET password_hash = $2, updated_at = now()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           string
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE app.users
SET email = $2, display_name = $3, updated_at = now()
WHERE id = $1
`

type UpdateUserProfileParams struct {
	ID          string
	Email       string
	DisplayName string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile, arg.ID, arg.Email, arg.DisplayName)
	return err
}
