// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppAiReview struct {
	ID            string
	WorkflowRunID string
	CommitSha     string
	Verdict       string
	Result        []byte
	CreatedAt     pgtype.Timestamptz
}

type AppAuditEvent struct {
	ID         int64
	ActorType  string
	ActorID    pgtype.Text
	Action     string
	TargetType string
	TargetID   string
	Payload    []byte
	CreatedAt  pgtype.Timestamptz
}

type AppExecution struct {
	ID                 string
	JobID              string
	ExecutionType      string
	Attempt            int32
	Status             string
	LeaseGeneration    int64
	StartedAt          pgtype.Timestamptz
	FinishedAt         pgtype.Timestamptz
	TimeoutSeconds     int32
	ExitCode           pgtype.Int4
	Result             []byte
	Error              []byte
	FailureFingerprint pgtype.Text
}

type AppHumanApproval struct {
	ID            string
	WorkflowRunID string
	CommitSha     string
	UserID        string
	Decision      string
	Comment       pgtype.Text
	CreatedAt     pgtype.Timestamptz
}

type AppIssue struct {
	ID                    string
	ProjectID             string
	Provider              string
	ExternalID            string
	DisplayNumber         string
	Title                 string
	Body                  string
	Url                   string
	State                 string
	Labels                []byte
	Priority              int32
	Eligible              bool
	HumanApprovalRequired bool
	ExternalCreatedAt     pgtype.Timestamptz
	ExternalUpdatedAt     pgtype.Timestamptz
	LastSyncedAt          pgtype.Timestamptz
	RawSnapshot           []byte
}

type AppIssueSyncState struct {
	ProjectID           string
	ConsecutiveFailures int32
	NextRetryAt         pgtype.Timestamptz
	LastError           pgtype.Text
	UpdatedAt           pgtype.Timestamptz
	LastSyncedAt        pgtype.Timestamptz
}

type AppJob struct {
	ID                string
	WorkflowRunID     string
	ProjectID         string
	RunnerID          pgtype.UUID
	Status            string
	LeaseGeneration   int64
	LastEventSequence int64
	LeaseExpiresAt    pgtype.Timestamptz
	OfferedAt         pgtype.Timestamptz
	AcceptedAt        pgtype.Timestamptz
	StartedAt         pgtype.Timestamptz
	FinishedAt        pgtype.Timestamptz
	RecoveryReason    pgtype.Text
}

type AppJobOffer struct {
	ID          string
	JobID       string
	RunnerID    string
	Status      string
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	RespondedAt pgtype.Timestamptz
}

type AppPipelineRun struct {
	ID            string
	WorkflowRunID string
	CommitSha     string
	Status        string
	Result        []byte
	StartedAt     pgtype.Timestamptz
	FinishedAt    pgtype.Timestamptz
}

type AppProject struct {
	ID                  string
	Name                string
	Enabled             bool
	RepositoryMode      string
	RepositoryUrl       pgtype.Text
	LocalRepositoryPath pgtype.Text
	DefaultBranch       string
	IssueTrackerType    string
	CodeHostType        string
	Configuration       []byte
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type AppProjectCircuitState struct {
	ProjectID           string
	State               string
	ConsecutiveFailures int32
	LastFailureReason   pgtype.Text
	OpenedAt            pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ProbeWorkflowRunID  pgtype.UUID
}

type AppProjectCredential struct {
	ProjectID  string
	Kind       string
	Ciphertext []byte
	Nonce      []byte
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	FilePath   string
}

type AppProjectLabel struct {
	ProjectID          string
	ReadyLabel         string
	RunningLabel       string
	ReviewLabel        string
	BlockedLabel       string
	HumanRequiredLabel string
	HumanApprovalLabel string
	FailedLabel        string
	DeliveredLabel     string
	PriorityPrefix     string
	DefaultPriority    int32
}

type AppProjectLock struct {
	ProjectID     string
	WorkflowRunID string
	AcquiredAt    pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type AppProjectPipelineStep struct {
	ID             string
	ProjectID      string
	Position       int32
	Name           string
	Command        string
	TimeoutSeconds int32
	Required       bool
	Environment    []byte
}

type AppProviderCircuitState struct {
	Provider            string
	State               string
	ConsecutiveFailures int32
	LastFailureReason   pgtype.Text
	OpenedAt            pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ProbeWorkflowRunID  pgtype.UUID
}

type AppPullRequest struct {
	ID            string
	WorkflowRunID string
	Provider      string
	ExternalID    string
	Url           string
	HeadCommit    string
	State         string
	MergedAt      pgtype.Timestamptz
	RawSnapshot   []byte
	MergeCommit   pgtype.Text
}

type AppRunner struct {
	ID               string
	Name             string
	Enabled          bool
	Draining         bool
	Status           string
	Version          string
	Labels           []byte
	Capabilities     []byte
	LastSeenAt       pgtype.Timestamptz
	RegisteredAt     pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	Capacity         int32
	OperatorDraining bool
}

type AppRunnerCredential struct {
	ID             string
	RunnerID       string
	CredentialHash string
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
}

type AppRunnerRegistrationToken struct {
	ID              string
	TokenHash       string
	CreatedByUserID pgtype.UUID
	AllowedLabels   []byte
	CreatedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	UsedAt          pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
}

type AppUser struct {
	ID           string
	Username     string
	PasswordHash string
	Role         string
	Enabled      bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	LastLoginAt  pgtype.Timestamptz
	Email        string
	DisplayName  string
}

type AppUserSession struct {
	ID             string
	UserID         string
	TokenHash      string
	CsrfTokenHash  string
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
	ClientMetadata []byte
}

type AppWorkflowCheckpoint struct {
	WorkflowRunID string
	Version       int64
	State         []byte
	CreatedAt     pgtype.Timestamptz
}

type AppWorkflowEvent struct {
	ID            int64
	WorkflowRunID string
	EventType     string
	Phase         pgtype.Text
	Severity      string
	Payload       []byte
	CreatedAt     pgtype.Timestamptz
}

type AppWorkflowExecutionRequest struct {
	ID            string
	WorkflowRunID string
	Role          string
	Attempt       int32
	Status        string
	CreatedAt     pgtype.Timestamptz
	DispatchedAt  pgtype.Timestamptz
}

type AppWorkflowRun struct {
	ID                      string
	ProjectID               string
	IssueID                 string
	ThreadID                string
	Status                  string
	CurrentPhase            string
	BranchName              pgtype.Text
	BaseCommit              pgtype.Text
	CurrentCommit           pgtype.Text
	PullRequestExternalID   pgtype.Text
	PullRequestUrl          pgtype.Text
	PlanningAttempts        int32
	ImplementationAttempts  int32
	PipelineRepairAttempts  int32
	ReviewCycles            int32
	CiRepairAttempts        int32
	TotalAgentExecutions    int32
	LastProgressAt          pgtype.Timestamptz
	LastFailureFingerprint  pgtype.Text
	BlockingReason          pgtype.Text
	TerminalReason          pgtype.Text
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	CompletedAt             pgtype.Timestamptz
	LastDiffHash            pgtype.Text
	NonProgressAttempts     int32
	ContinuationAttempts    int32
	LastDeliveryOutcome     pgtype.Text
	LastGateVerdict         pgtype.Text
	RemainingWork           []byte
	HumanQuestion           pgtype.Text
	HumanResumePhase        pgtype.Text
	HumanGuidance           pgtype.Text
	GithubCheckPollAttempts int32
	SupersededAt            pgtype.Timestamptz
}

type AppWorkflowTransitionOutbox struct {
	ID                  string
	WorkflowRunID       string
	NewStatus           string
	StateUpdates        []byte
	Status              string
	Attempts            int32
	LastError           pgtype.Text
	CreatedAt           pgtype.Timestamptz
	ProcessedAt         pgtype.Timestamptz
	ProcessingStartedAt pgtype.Timestamptz
}

type LanggraphCheckpoint struct {
	ThreadID           string
	CheckpointID       string
	ParentCheckpointID pgtype.Text
	Checkpoint         []byte
	Metadata           []byte
	CreatedAt          pgtype.Timestamptz
}

type LanggraphCheckpointWrite struct {
	ThreadID     string
	CheckpointID string
	TaskID       string
	Idx          int32
	Channel      string
	Type         pgtype.Text
	Value        []byte
}
