// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptJob(ctx context.Context, arg AcceptJobParams) (AcceptJobRow, error)
	// DeleteProjectLock lives in delivery.sql (identical statement, already
	// generated there); reused as-is rather than duplicated.
	AcceptJobOffer(ctx context.Context, arg AcceptJobOfferParams) (string, error)
	CancelExpiredLeaseJobs(ctx context.Context, reason pgtype.Text) ([]string, error)
	CancelJob(ctx context.Context, arg CancelJobParams) error
	CancelJobOfferByJob(ctx context.Context, jobID string) error
	CancelJobOfferByRunner(ctx context.Context, arg CancelJobOfferByRunnerParams) error
	CancelOfferedJob(ctx context.Context, arg CancelOfferedJobParams) error
	CancelUnansweredOfferJobs(ctx context.Context, arg CancelUnansweredOfferJobsParams) ([]string, error)
	CancelWorkflowExecutionRequests(ctx context.Context, workflowRunID string) error
	CancelWorkflowJobOffers(ctx context.Context, workflowRunID string) error
	CancelWorkflowJobs(ctx context.Context, arg CancelWorkflowJobsParams) (CancelWorkflowJobsRow, error)
	CancelWorkflowRunOfferRejected(ctx context.Context, id string) error
	CancelWorkflowRunUndelivered(ctx context.Context, arg CancelWorkflowRunUndeliveredParams) error
	// A runner's in-flight job count is compared against its own registered
	// capacity (app.runners.capacity, see migration 003) rather than excluding it
	// the instant it holds any job at all: that used to hard-cap every runner at
	// one concurrent execution regardless of what it advertised at registration.
	// The count is still scoped to this runner (j.runner_id = r.id) so it says
	// nothing about any other runner's load, and FOR UPDATE OF i, r still locks
	// exactly the issue and runner rows a concurrent ClaimSchedulableIssue would
	// also need, so SKIP LOCKED continues to hand a racing caller a different
	// issue/runner pair instead of double-booking this one.
	ClaimSchedulableIssue(ctx context.Context, runnerIds []string) (ClaimSchedulableIssueRow, error)
	CountProjectIssues(ctx context.Context, projectID string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) error
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error
	CreateJob(ctx context.Context, arg CreateJobParams) error
	CreateJobOffer(ctx context.Context, arg CreateJobOfferParams) error
	CreateProject(ctx context.Context, arg CreateProjectParams) error
	CreateProjectLock(ctx context.Context, arg CreateProjectLockParams) (int64, error)
	CreateProjectPipelineStep(ctx context.Context, arg CreateProjectPipelineStepParams) error
	CreateRetryEvent(ctx context.Context, workflowRunID string) error
	CreateRunner(ctx context.Context, arg CreateRunnerParams) error
	CreateRunnerCredential(ctx context.Context, arg CreateRunnerCredentialParams) error
	CreateRunnerRegistrationToken(ctx context.Context, arg CreateRunnerRegistrationTokenParams) (pgtype.Timestamptz, error)
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) error
	CreateWorkflowEvent(ctx context.Context, arg CreateWorkflowEventParams) error
	CreateWorkflowRun(ctx context.Context, arg CreateWorkflowRunParams) error
	DeleteProjectCredential(ctx context.Context, arg DeleteProjectCredentialParams) (int64, error)
	DeleteProjectLock(ctx context.Context, arg DeleteProjectLockParams) error
	DeleteProjectLockByWorkflow(ctx context.Context, workflowRunID string) error
	DeleteProjectPipelineSteps(ctx context.Context, projectID string) error
	DrainRunner(ctx context.Context, id string) (int64, error)
	EnableRunner(ctx context.Context, id string) (int64, error)
	ExpireUnansweredOffers(ctx context.Context, unansweredOffer pgtype.Interval) error
	// Used only when MarkWorkflowCompleted's guard above misses: GitHub has
	// already confirmed the pull request merged (observeWorkflow calls this only
	// after that), which is irreversible, regardless of what this run's status
	// column raced to in the meantime (an operator cancelling it, abandonedChecks
	// blocking it, or anything else). The WHERE clause deliberately does not
	// repeat the 'waiting_github_checks' guard: the merge is a fact this write
	// must land no matter which status it finds. previous_status lets the caller
	// log what the race actually was.
	ForceWorkflowCompleted(ctx context.Context, id string) (string, error)
	GetDeliveryWorkflow(ctx context.Context, id string) (GetDeliveryWorkflowRow, error)
	GetFencedJobProject(ctx context.Context, arg GetFencedJobProjectParams) (string, error)
	GetJobForOfferReject(ctx context.Context, arg GetJobForOfferRejectParams) (GetJobForOfferRejectRow, error)
	GetProject(ctx context.Context, id string) (GetProjectRow, error)
	GetProjectCredentialSecret(ctx context.Context, arg GetProjectCredentialSecretParams) (GetProjectCredentialSecretRow, error)
	GetRunner(ctx context.Context, id string) (GetRunnerRow, error)
	GetRunnerCredentialHash(ctx context.Context, id string) (string, error)
	// The oldest heartbeat is returned as a raw timestamp (rather than an
	// already-subtracted epoch age) plus the database's own now(), so the
	// nullability of "no enabled runner" survives sqlc's type inference as a
	// pgtype.Timestamptz.Valid flag instead of silently becoming a NOT NULL
	// float64 that panics on a NULL scan -- see the Go call site for the
	// subtraction, which still uses only values this same statement read from
	// the database's clock.
	GetSchedulerSnapshot(ctx context.Context) (GetSchedulerSnapshotRow, error)
	GetSessionActor(ctx context.Context, tokenHash string) (GetSessionActorRow, error)
	GetSessionCSRFHash(ctx context.Context, tokenHash string) (string, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	GetUserForUpdate(ctx context.Context, id string) (GetUserForUpdateRow, error)
	GetUserProfile(ctx context.Context, id string) (GetUserProfileRow, error)
	// pr.external_id/pr.url and wr.pull_request_external_id/wr.pull_request_url are
	// combined in Go rather than with SQL COALESCE: sqlc's nullability inference
	// does not reliably propagate through COALESCE of two nullable columns (one
	// from an outer join), and mistyping either side NOT NULL would panic the
	// very first workflow scanned before a pull request exists.
	GetWorkflowDetail(ctx context.Context, id string) (GetWorkflowDetailRow, error)
	GetWorkflowForControl(ctx context.Context, id string) (GetWorkflowForControlRow, error)
	InsertPullRequestCreatedEvent(ctx context.Context, arg InsertPullRequestCreatedEventParams) error
	InsertPullRequestMergedEvent(ctx context.Context, workflowRunID string) error
	InsertWorkflowTerminationEvent(ctx context.Context, arg InsertWorkflowTerminationEventParams) error
	// eligible_count matches the scheduler's own candidate set (ListQueueEntries,
	// ClaimSchedulableIssue), not the bare label bit: an issue opted in by label
	// but sitting on a failed, blocked or delivered run that has not been
	// superseded by a retry is not actually schedulable, and the sidebar badge
	// would otherwise overcount it.
	IssueSyncStatusEntries(ctx context.Context) ([]IssueSyncStatusEntriesRow, error)
	ListProjectCredentials(ctx context.Context, projectID string) ([]ListProjectCredentialsRow, error)
	ListProjectIDs(ctx context.Context) ([]string, error)
	ListProjectPipelineSteps(ctx context.Context, projectID string) ([]ListProjectPipelineStepsRow, error)
	// Used by the unattended sync loop only (SyncProjects): a project whose last
	// failure set app.issue_sync_state.next_retry_at in the future (see
	// UpsertIssueSyncStateFailure's exponential backoff) is skipped so a
	// repository with a revoked token or a deleted remote is not hammered on
	// every tick forever. The operator-triggered "Sync now" path (SyncNow) goes
	// through ListSyncableProjects/ListSyncableProjectByID instead and always
	// bypasses backoff, since a human explicitly asking for a sync right now is
	// exactly the case backoff should not stand in front of.
	ListProjectsDueForSync(ctx context.Context) ([]ListProjectsDueForSyncRow, error)
	ListQueueEntries(ctx context.Context, limit int32) ([]ListQueueEntriesRow, error)
	ListRunnerRegistrationTokens(ctx context.Context) ([]ListRunnerRegistrationTokensRow, error)
	ListRunners(ctx context.Context) ([]ListRunnersRow, error)
	ListSyncableProjectByID(ctx context.Context, id string) ([]ListSyncableProjectByIDRow, error)
	ListSyncableProjects(ctx context.Context) ([]ListSyncableProjectsRow, error)
	ListWorkflowEvents(ctx context.Context, arg ListWorkflowEventsParams) ([]ListWorkflowEventsRow, error)
	// Replaces the old ListWorkflowIDs + one GetWorkflowDetail per row: that shape
	// was O(all workflow runs) in both rows and queries, and app.workflow_runs
	// only grows. This does the same join GetWorkflowDetail does, once, for the
	// most recent $1 rows -- see the pr.external_id/wr.pull_request_external_id
	// comment on GetWorkflowDetail below for why those aren't COALESCEd in SQL.
	ListWorkflowsPage(ctx context.Context, limit int32) ([]ListWorkflowsPageRow, error)
	MarkPullRequestMerged(ctx context.Context, workflowRunID string) error
	MarkRegistrationTokenUsed(ctx context.Context, id string) error
	MarkStaleRunnersOffline(ctx context.Context, staleRunner pgtype.Interval) error
	MarkWorkflowCompleted(ctx context.Context, id string) (int64, error)
	MarkWorkflowDelivered(ctx context.Context, id string) (int64, error)
	ProjectExists(ctx context.Context, id string) (bool, error)
	RecordJobExecutionEvent(ctx context.Context, arg RecordJobExecutionEventParams) (string, error)
	RecordRunnerHeartbeat(ctx context.Context, arg RecordRunnerHeartbeatParams) error
	// Bumps the count of consecutive transient GitHub failures blockOrRetryExternal
	// (delivery.go) has absorbed for this run without moving its status, and
	// returns the new count so the caller can decide whether to keep retrying or
	// fall through to blockExternal. updated_at advances with it so a transient
	// failure during 'delivering' also pushes back resumeStrandedDeliveries'
	// re-drive window (recovery.go's strandedDelivery), which is what turns
	// these retries into spaced-out attempts instead of a tight loop.
	RecordTransientDeliveryFailure(ctx context.Context, id string) (int32, error)
	RenewJobLease(ctx context.Context, arg RenewJobLeaseParams) (pgtype.Timestamptz, error)
	RevokeOtherUserSessions(ctx context.Context, arg RevokeOtherUserSessionsParams) error
	RevokeRunner(ctx context.Context, id string) (int64, error)
	RevokeRunnerCredentials(ctx context.Context, runnerID string) error
	RevokeRunnerRegistrationToken(ctx context.Context, id string) (RevokeRunnerRegistrationTokenRow, error)
	RevokeSessionByTokens(ctx context.Context, arg RevokeSessionByTokensParams) (int64, error)
	SelectAbandonedChecksWorkflows(ctx context.Context, abandonedChecks pgtype.Interval) ([]string, error)
	SelectStrandedDeliveryWorkflows(ctx context.Context, strandedDelivery pgtype.Interval) ([]string, error)
	SelectValidRegistrationToken(ctx context.Context, arg SelectValidRegistrationTokenParams) (string, error)
	SelectWaitingGithubChecksWorkflows(ctx context.Context) ([]string, error)
	SetProjectEnabled(ctx context.Context, arg SetProjectEnabledParams) (int64, error)
	SetRunnerDraining(ctx context.Context, arg SetRunnerDrainingParams) error
	SetWorkflowControlStatus(ctx context.Context, arg SetWorkflowControlStatusParams) error
	SetWorkflowPreparing(ctx context.Context, id string) error
	SetWorkflowTerminalStatus(ctx context.Context, arg SetWorkflowTerminalStatusParams) error
	// Retry no longer writes app.issues.eligible directly (see #268 and migration
	// 023): the issue's eligible bit stays purely label-driven, and marking this
	// run superseded is what lets the scheduler's app.workflow_runs join stop
	// excluding its issue on this run's account. A fresh run is what actually
	// reopens the work; this only clears the way for one.
	SupersedeWorkflowRun(ctx context.Context, id string) error
	TerminateWorkflowRun(ctx context.Context, arg TerminateWorkflowRunParams) (string, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (int64, error)
	UpdateProjectCredentialSecret(ctx context.Context, arg UpdateProjectCredentialSecretParams) (int64, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	// eligible is written unconditionally from the tracker's labels (see
	// issuePriority) on every sync, full stop -- it is not the scheduler's
	// candidate signal by itself any more (see ListQueueEntries and
	// ClaimSchedulableIssue's app.workflow_runs.superseded_at join for that), so
	// there is no lifecycle state left here for a sync to clobber. See #268 and
	// migration 023 for why a CASE guarding this used to live here.
	//
	// state is now written from what GitHub itself reports (ListIssues fetches
	// --state all, not just open) rather than being hardcoded to 'open': every
	// scheduling query (ListQueueEntries, GetSchedulerSnapshot,
	// ClaimSchedulableIssue) already filters on i.state = 'open', so an issue
	// closed on the tracker stops being schedulable the moment this reconciles
	// it, with no separate lifecycle write required. The caller also ANDs
	// eligible with "still open on the tracker", so a closed issue is reported
	// ineligible too, not just excluded via state.
	// The DO UPDATE's WHERE guard (added for #290) is what keeps a steady-state
	// sync pass -- nothing changed on the tracker since the last one -- from
	// rewriting every issue row, full raw_snapshot JSONB included, on every
	// single pass. Without it, Postgres has no way to know the SET list would
	// produce an identical row and pays a full tuple write (and a fresh xmin,
	// and a dead tuple for autovacuum to reclaim) regardless. The comparison
	// covers every column the SET list actually writes from EXCLUDED except
	// last_synced_at itself (which always advances and would otherwise defeat
	// the guard by always differing); a row with no other change simply keeps
	// its previous last_synced_at rather than that column alone forcing a write.
	UpsertIssue(ctx context.Context, arg UpsertIssueParams) error
	// next_retry_at backs off exponentially with consecutive_failures (1 minute,
	// 2, 4, 8, ...), capped at 1 hour. The exponent itself is capped (via the
	// inner LEAST) before POWER ever sees it, rather than relying on the outer
	// LEAST against '1 hour' alone: POWER(2, n) is evaluated first, and an
	// uncapped n for a project that has been failing for days would overflow
	// double precision (and then interval multiplication) before that outer
	// LEAST ever got a chance to clamp the result.
	UpsertIssueSyncStateFailure(ctx context.Context, arg UpsertIssueSyncStateFailureParams) error
	// next_retry_at is reset to NULL on success: leaving a stale future timestamp
	// around after a project recovers would keep ListProjectsDueForSync skipping
	// it long after there is anything to back off from.
	UpsertIssueSyncStateSuccess(ctx context.Context, projectID string) error
	UpsertProjectCredential(ctx context.Context, arg UpsertProjectCredentialParams) (int64, error)
	UpsertPullRequest(ctx context.Context, arg UpsertPullRequestParams) error
	UpsertSeedRunnerRegistrationToken(ctx context.Context, arg UpsertSeedRunnerRegistrationTokenParams) error
}

var _ Querier = (*Queries)(nil)
