// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: recovery.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelExpiredLeaseJobs = `-- name: CancelExpiredLeaseJobs :many
UPDATE app.jobs
SET status = 'cancelled', finished_at = now(), lease_generation = lease_generation + 1,
    recovery_reason = $1
WHERE status IN ('preparing', 'running') AND lease_expires_at < now()
RETURNING workflow_run_id::text AS workflow_run_id
`

func (q *Queries) CancelExpiredLeaseJobs(ctx context.Context, reason pgtype.Text) ([]string, error) {
	rows, err := q.db.Query(ctx, cancelExpiredLeaseJobs, reason)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var workflow_run_id string
		if err := rows.Scan(&workflow_run_id); err != nil {
			return nil, err
		}
		items = append(items, workflow_run_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelUnansweredOfferJobs = `-- name: CancelUnansweredOfferJobs :many
UPDATE app.jobs
SET status = 'cancelled', finished_at = now(), lease_generation = lease_generation + 1,
    recovery_reason = $1
WHERE status = 'offered' AND offered_at < now() - $2::interval
RETURNING workflow_run_id::text AS workflow_run_id
`

type CancelUnansweredOfferJobsParams struct {
	Reason          pgtype.Text
	UnansweredOffer pgtype.Interval
}

func (q *Queries) CancelUnansweredOfferJobs(ctx context.Context, arg CancelUnansweredOfferJobsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, cancelUnansweredOfferJobs, arg.Reason, arg.UnansweredOffer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var workflow_run_id string
		if err := rows.Scan(&workflow_run_id); err != nil {
			return nil, err
		}
		items = append(items, workflow_run_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireUnansweredOffers = `-- name: ExpireUnansweredOffers :exec
UPDATE app.job_offers
SET status = 'expired', responded_at = now()
WHERE status = 'offered'
  AND job_id IN (
    SELECT id FROM app.jobs
    WHERE status = 'offered' AND offered_at < now() - $1::interval
  )
`

func (q *Queries) ExpireUnansweredOffers(ctx context.Context, unansweredOffer pgtype.Interval) error {
	_, err := q.db.Exec(ctx, expireUnansweredOffers, unansweredOffer)
	return err
}

const markStaleRunnersOffline = `-- name: MarkStaleRunnersOffline :exec
UPDATE app.runners
SET status = 'offline'
WHERE status = 'online'
  AND (last_seen_at IS NULL OR last_seen_at < now() - $1::interval)
`

func (q *Queries) MarkStaleRunnersOffline(ctx context.Context, staleRunner pgtype.Interval) error {
	_, err := q.db.Exec(ctx, markStaleRunnersOffline, staleRunner)
	return err
}

const selectAbandonedChecksWorkflows = `-- name: SelectAbandonedChecksWorkflows :many
SELECT id::text AS id
FROM app.workflow_runs
WHERE status = 'waiting_github_checks' AND updated_at < now() - $1::interval
ORDER BY updated_at, id
LIMIT 20
`

func (q *Queries) SelectAbandonedChecksWorkflows(ctx context.Context, abandonedChecks pgtype.Interval) ([]string, error) {
	rows, err := q.db.Query(ctx, selectAbandonedChecksWorkflows, abandonedChecks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectStrandedDeliveryWorkflows = `-- name: SelectStrandedDeliveryWorkflows :many
SELECT wr.id::text AS id
FROM app.workflow_runs wr
JOIN app.project_locks l ON l.workflow_run_id = wr.id
WHERE wr.status = 'completed' AND wr.updated_at < now() - $1::interval
ORDER BY wr.updated_at, wr.id
LIMIT 20
`

func (q *Queries) SelectStrandedDeliveryWorkflows(ctx context.Context, strandedDelivery pgtype.Interval) ([]string, error) {
	rows, err := q.db.Query(ctx, selectStrandedDeliveryWorkflows, strandedDelivery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
