// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: review.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestAiReview = `-- name: GetLatestAiReview :one
SELECT verdict FROM app.ai_reviews WHERE workflow_run_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestAiReview(ctx context.Context, workflowRunID string) (string, error) {
	row := q.db.QueryRow(ctx, getLatestAiReview, workflowRunID)
	var verdict string
	err := row.Scan(&verdict)
	return verdict, err
}

const getProjectConfigForWorkflow = `-- name: GetProjectConfigForWorkflow :one
SELECT p.configuration
FROM app.workflow_runs wr
JOIN app.projects p ON p.id = wr.project_id
WHERE wr.id = $1
`

// persistExecutionEvent reads this once per developer "completed" event to
// decide whether the project opted into EnableAiReview (server.go's
// projectConfig) -- a project that never touches this key behaves exactly as
// it always has.
func (q *Queries) GetProjectConfigForWorkflow(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getProjectConfigForWorkflow, id)
	var configuration []byte
	err := row.Scan(&configuration)
	return configuration, err
}

const getReviewDispatchWorkflow = `-- name: GetReviewDispatchWorkflow :one
SELECT wr.project_id::text AS project_id, i.external_id, i.title, i.body,
       p.repository_mode, COALESCE(p.repository_url, '') AS repository_url,
       COALESCE(p.local_repository_path, '') AS local_repository_path,
       p.default_branch, COALESCE(wr.branch_name, '') AS branch_name,
       p.configuration, wr.review_cycles, j.id::text AS job_id
FROM app.workflow_runs wr
JOIN app.issues i ON i.id = wr.issue_id
JOIN app.projects p ON p.id = wr.project_id
JOIN app.jobs j ON j.workflow_run_id = wr.id
WHERE wr.id = $1 AND wr.status = 'waiting_ai_review' AND j.role = 'developer' AND j.status = 'completed'
`

type GetReviewDispatchWorkflowRow struct {
	ProjectID           string
	ExternalID          string
	Title               string
	Body                string
	RepositoryMode      string
	RepositoryUrl       string
	LocalRepositoryPath string
	DefaultBranch       string
	BranchName          string
	Configuration       []byte
	ReviewCycles        int32
	JobID               string
}

// Everything dispatchReviewerJob (review.go) needs to build and offer a
// fresh, independent reviewer execution against the one job a workflow run
// already has. Guarded on the run's own status and the job's own role and
// status: only a run sitting at 'waiting_ai_review' whose job is still the
// completed developer job is ever reviewable, so a concurrent or repeated
// dispatch attempt (the recovery sweep racing the inline call
// persistExecutionEvent already made) finds no row and is a no-op rather than
// a double dispatch.
func (q *Queries) GetReviewDispatchWorkflow(ctx context.Context, id string) (GetReviewDispatchWorkflowRow, error) {
	row := q.db.QueryRow(ctx, getReviewDispatchWorkflow, id)
	var i GetReviewDispatchWorkflowRow
	err := row.Scan(
		&i.ProjectID,
		&i.ExternalID,
		&i.Title,
		&i.Body,
		&i.RepositoryMode,
		&i.RepositoryUrl,
		&i.LocalRepositoryPath,
		&i.DefaultBranch,
		&i.BranchName,
		&i.Configuration,
		&i.ReviewCycles,
		&i.JobID,
	)
	return i, err
}

const incrementReviewCycles = `-- name: IncrementReviewCycles :exec
UPDATE app.workflow_runs SET review_cycles = review_cycles + 1, updated_at = now() WHERE id = $1
`

func (q *Queries) IncrementReviewCycles(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementReviewCycles, id)
	return err
}

const insertAiReview = `-- name: InsertAiReview :exec
INSERT INTO app.ai_reviews(id, workflow_run_id, commit_sha, verdict, result)
VALUES ($1, $2, $3, $4, $5::jsonb)
`

type InsertAiReviewParams struct {
	ID            string
	WorkflowRunID string
	CommitSha     string
	Verdict       string
	Result        []byte
}

func (q *Queries) InsertAiReview(ctx context.Context, arg InsertAiReviewParams) error {
	_, err := q.db.Exec(ctx, insertAiReview,
		arg.ID,
		arg.WorkflowRunID,
		arg.CommitSha,
		arg.Verdict,
		arg.Result,
	)
	return err
}

const markWorkflowReviewApproved = `-- name: MarkWorkflowReviewApproved :execrows
UPDATE app.workflow_runs
SET status = 'delivering', current_phase = 'delivering', updated_at = now()
WHERE id = $1 AND status = 'waiting_ai_review'
`

// An approving verdict's handoff to deliverWorkflow, which itself requires
// 'delivering' (MarkWorkflowDelivered's own guard) -- the same status a
// developer's own "completed" event moves a run through when AI review is
// disabled. Guarded on 'waiting_ai_review' so this is a no-op rather than a
// double transition if it ever raced another caller.
func (q *Queries) MarkWorkflowReviewApproved(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, markWorkflowReviewApproved, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reopenJobForReview = `-- name: ReopenJobForReview :one
UPDATE app.jobs
SET role = 'reviewer', runner_id = $1::uuid, status = 'offered',
    offered_at = now(), accepted_at = NULL, started_at = NULL, finished_at = NULL,
    last_event_sequence = 0, lease_generation = lease_generation + 1, recovery_reason = NULL
WHERE id = $2 AND role = 'developer' AND status = 'completed'
RETURNING lease_generation
`

type ReopenJobForReviewParams struct {
	RunnerID string
	ID       string
}

// Reuses the workflow run's single job row for a second, independent
// execution instead of inserting a new one (app.jobs.workflow_run_id stays
// UNIQUE). Guarded on the job still being the completed developer job, the
// same guard GetReviewDispatchWorkflow reads under -- a second caller that
// raced this one finds 0 rows affected and does nothing further.
func (q *Queries) ReopenJobForReview(ctx context.Context, arg ReopenJobForReviewParams) (int64, error) {
	row := q.db.QueryRow(ctx, reopenJobForReview, arg.RunnerID, arg.ID)
	var lease_generation int64
	err := row.Scan(&lease_generation)
	return lease_generation, err
}

const selectEligibleReviewRunner = `-- name: SelectEligibleReviewRunner :one
SELECT r.id::text AS runner_id
FROM app.runners r
WHERE r.status = 'online' AND r.enabled AND NOT r.draining AND r.revoked_at IS NULL
  AND r.id::text = ANY($1::text[])
  AND r.labels @> $2::jsonb
  AND (SELECT COUNT(*) FROM app.jobs j WHERE j.runner_id = r.id AND j.status IN ('offered', 'preparing', 'running')) < r.capacity
ORDER BY r.id
LIMIT 1
`

type SelectEligibleReviewRunnerParams struct {
	RunnerIds      []string
	RequiredLabels []byte
}

// Picks a runner to hand the reviewer packet to, restricted to the connected
// set the caller already holds gRPC control streams for (sqlc.arg(runner_ids)).
// Deliberately simpler than ClaimSchedulableIssue: there is no competing
// issue to arbitrate over here, only one workflow's one review, so this reads
// without FOR UPDATE/SKIP LOCKED -- a race loses at ReopenJobForReview's own
// guard instead, which is a cheap, harmless no-op.
func (q *Queries) SelectEligibleReviewRunner(ctx context.Context, arg SelectEligibleReviewRunnerParams) (string, error) {
	row := q.db.QueryRow(ctx, selectEligibleReviewRunner, arg.RunnerIds, arg.RequiredLabels)
	var runner_id string
	err := row.Scan(&runner_id)
	return runner_id, err
}

const selectStrandedReviewDispatchWorkflows = `-- name: SelectStrandedReviewDispatchWorkflows :many
SELECT wr.id::text AS id
FROM app.workflow_runs wr
JOIN app.jobs j ON j.workflow_run_id = wr.id
WHERE wr.status = 'waiting_ai_review' AND j.role = 'developer' AND j.status = 'completed'
  AND wr.updated_at < now() - $1::interval
ORDER BY wr.updated_at, wr.id
LIMIT 20
`

// resumeStrandedReviewDispatches' (recovery.go) candidate set: a run whose
// developer execution completed and whose project opted into AI review, but
// whose inline dispatchReviewerJob call never actually offered a reviewer job
// -- typically because no runner was connected yet. The same guard
// GetReviewDispatchWorkflow uses (job still the completed developer job)
// doubles as "dispatch has not happened yet", so a run this sweep already
// redispatched successfully stops matching on its own.
func (q *Queries) SelectStrandedReviewDispatchWorkflows(ctx context.Context, strandedReview pgtype.Interval) ([]string, error) {
	rows, err := q.db.Query(ctx, selectStrandedReviewDispatchWorkflows, strandedReview)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectStrandedReviewVerdictWorkflows = `-- name: SelectStrandedReviewVerdictWorkflows :many
SELECT wr.id::text AS id
FROM app.workflow_runs wr
JOIN app.jobs j ON j.workflow_run_id = wr.id
WHERE wr.status = 'waiting_ai_review' AND j.role = 'reviewer' AND j.status = 'completed'
  AND wr.updated_at < now() - $1::interval
ORDER BY wr.updated_at, wr.id
LIMIT 20
`

// resumeStrandedReviewVerdicts' (recovery.go) candidate set: a reviewer
// execution finished (the job is 'completed' with role 'reviewer'), but the
// run is still sitting at 'waiting_ai_review' -- persistExecutionEvent
// committed the terminal event, then the process died before
// handleReviewCompletion's follow-on delivery/block decision landed.
func (q *Queries) SelectStrandedReviewVerdictWorkflows(ctx context.Context, strandedReview pgtype.Interval) ([]string, error) {
	rows, err := q.db.Query(ctx, selectStrandedReviewVerdictWorkflows, strandedReview)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
