// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: server_projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProjectIssues = `-- name: CountProjectIssues :one
SELECT COUNT(*) FROM app.issues WHERE project_id = $1
`

func (q *Queries) CountProjectIssues(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectIssues, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :exec
INSERT INTO app.projects (id, name, repository_mode, repository_url, local_repository_path, default_branch, configuration)
VALUES ($1, $2, $3, NULLIF($4, ''), NULLIF($5, ''), $6, $7::jsonb)
`

type CreateProjectParams struct {
	ID             string
	Name           string
	RepositoryMode string
	Column4        interface{}
	Column5        interface{}
	DefaultBranch  string
	Column7        []byte
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.Exec(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.RepositoryMode,
		arg.Column4,
		arg.Column5,
		arg.DefaultBranch,
		arg.Column7,
	)
	return err
}

const createProjectPipelineStep = `-- name: CreateProjectPipelineStep :exec
INSERT INTO app.project_pipeline_steps(id, project_id, position, name, command, timeout_seconds, required)
VALUES ($1, $2, $3, $4, $4, $5, $6)
`

type CreateProjectPipelineStepParams struct {
	ID             string
	ProjectID      string
	Position       int32
	Name           string
	TimeoutSeconds int32
	Required       bool
}

func (q *Queries) CreateProjectPipelineStep(ctx context.Context, arg CreateProjectPipelineStepParams) error {
	_, err := q.db.Exec(ctx, createProjectPipelineStep,
		arg.ID,
		arg.ProjectID,
		arg.Position,
		arg.Name,
		arg.TimeoutSeconds,
		arg.Required,
	)
	return err
}

const deleteProjectPipelineSteps = `-- name: DeleteProjectPipelineSteps :exec
DELETE FROM app.project_pipeline_steps WHERE project_id = $1
`

func (q *Queries) DeleteProjectPipelineSteps(ctx context.Context, projectID string) error {
	_, err := q.db.Exec(ctx, deleteProjectPipelineSteps, projectID)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id::text AS id, name, enabled, repository_mode, repository_url, local_repository_path, default_branch, configuration::text AS configuration
FROM app.projects
WHERE id = $1
`

type GetProjectRow struct {
	ID                  string
	Name                string
	Enabled             bool
	RepositoryMode      string
	RepositoryUrl       pgtype.Text
	LocalRepositoryPath pgtype.Text
	DefaultBranch       string
	Configuration       string
}

func (q *Queries) GetProject(ctx context.Context, id string) (GetProjectRow, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i GetProjectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.RepositoryMode,
		&i.RepositoryUrl,
		&i.LocalRepositoryPath,
		&i.DefaultBranch,
		&i.Configuration,
	)
	return i, err
}

const issueSyncStatusEntries = `-- name: IssueSyncStatusEntries :many
SELECT p.id::text AS id, p.name, p.enabled, COUNT(i.id) AS issue_count,
       COUNT(i.id) FILTER(WHERE i.eligible AND i.state = 'open' AND NOT EXISTS (
         SELECT 1 FROM app.workflow_runs w
         WHERE w.issue_id = i.id AND w.superseded_at IS NULL AND w.status IN ('failed', 'blocked', 'completed')
       )) AS eligible_count,
       s.last_synced_at, s.consecutive_failures, s.next_retry_at, s.last_error
FROM app.projects p
LEFT JOIN app.issues i ON i.project_id = p.id
LEFT JOIN app.issue_sync_state s ON s.project_id = p.id
GROUP BY p.id, p.name, p.enabled, s.last_synced_at, s.consecutive_failures, s.next_retry_at, s.last_error
ORDER BY p.name, p.id
`

type IssueSyncStatusEntriesRow struct {
	ID                  string
	Name                string
	Enabled             bool
	IssueCount          int64
	EligibleCount       int64
	LastSyncedAt        pgtype.Timestamptz
	ConsecutiveFailures pgtype.Int4
	NextRetryAt         pgtype.Timestamptz
	LastError           pgtype.Text
}

// eligible_count matches the scheduler's own candidate set (ListQueueEntries,
// ClaimSchedulableIssue), not the bare label bit: an issue opted in by label
// but sitting on a failed, blocked or delivered run that has not been
// superseded by a retry is not actually schedulable, and the sidebar badge
// would otherwise overcount it.
func (q *Queries) IssueSyncStatusEntries(ctx context.Context) ([]IssueSyncStatusEntriesRow, error) {
	rows, err := q.db.Query(ctx, issueSyncStatusEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IssueSyncStatusEntriesRow
	for rows.Next() {
		var i IssueSyncStatusEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.IssueCount,
			&i.EligibleCount,
			&i.LastSyncedAt,
			&i.ConsecutiveFailures,
			&i.NextRetryAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectIDs = `-- name: ListProjectIDs :many
SELECT id::text AS id FROM app.projects ORDER BY name, id
`

func (q *Queries) ListProjectIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listProjectIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectPipelineSteps = `-- name: ListProjectPipelineSteps :many
SELECT command, timeout_seconds, position, required
FROM app.project_pipeline_steps
WHERE project_id = $1
ORDER BY position, id
`

type ListProjectPipelineStepsRow struct {
	Command        string
	TimeoutSeconds int32
	Position       int32
	Required       bool
}

func (q *Queries) ListProjectPipelineSteps(ctx context.Context, projectID string) ([]ListProjectPipelineStepsRow, error) {
	rows, err := q.db.Query(ctx, listProjectPipelineSteps, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectPipelineStepsRow
	for rows.Next() {
		var i ListProjectPipelineStepsRow
		if err := rows.Scan(
			&i.Command,
			&i.TimeoutSeconds,
			&i.Position,
			&i.Required,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsDueForSync = `-- name: ListProjectsDueForSync :many
SELECT p.id::text AS id, p.repository_url
FROM app.projects p
LEFT JOIN app.issue_sync_state s ON s.project_id = p.id
WHERE p.enabled AND (s.next_retry_at IS NULL OR s.next_retry_at <= now())
`

type ListProjectsDueForSyncRow struct {
	ID            string
	RepositoryUrl pgtype.Text
}

// Used by the unattended sync loop only (SyncProjects): a project whose last
// failure set app.issue_sync_state.next_retry_at in the future (see
// UpsertIssueSyncStateFailure's exponential backoff) is skipped so a
// repository with a revoked token or a deleted remote is not hammered on
// every tick forever. The operator-triggered "Sync now" path (SyncNow) goes
// through ListSyncableProjects/ListSyncableProjectByID instead and always
// bypasses backoff, since a human explicitly asking for a sync right now is
// exactly the case backoff should not stand in front of.
func (q *Queries) ListProjectsDueForSync(ctx context.Context) ([]ListProjectsDueForSyncRow, error) {
	rows, err := q.db.Query(ctx, listProjectsDueForSync)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsDueForSyncRow
	for rows.Next() {
		var i ListProjectsDueForSyncRow
		if err := rows.Scan(&i.ID, &i.RepositoryUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncableProjectByID = `-- name: ListSyncableProjectByID :many
SELECT id::text AS id, repository_url
FROM app.projects
WHERE enabled AND id = $1
`

type ListSyncableProjectByIDRow struct {
	ID            string
	RepositoryUrl pgtype.Text
}

func (q *Queries) ListSyncableProjectByID(ctx context.Context, id string) ([]ListSyncableProjectByIDRow, error) {
	rows, err := q.db.Query(ctx, listSyncableProjectByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSyncableProjectByIDRow
	for rows.Next() {
		var i ListSyncableProjectByIDRow
		if err := rows.Scan(&i.ID, &i.RepositoryUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncableProjects = `-- name: ListSyncableProjects :many
SELECT id::text AS id, repository_url
FROM app.projects
WHERE enabled
`

type ListSyncableProjectsRow struct {
	ID            string
	RepositoryUrl pgtype.Text
}

func (q *Queries) ListSyncableProjects(ctx context.Context) ([]ListSyncableProjectsRow, error) {
	rows, err := q.db.Query(ctx, listSyncableProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSyncableProjectsRow
	for rows.Next() {
		var i ListSyncableProjectsRow
		if err := rows.Scan(&i.ID, &i.RepositoryUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectEnabled = `-- name: SetProjectEnabled :execrows
UPDATE app.projects SET enabled = $2, updated_at = now() WHERE id = $1
`

type SetProjectEnabledParams struct {
	ID      string
	Enabled bool
}

func (q *Queries) SetProjectEnabled(ctx context.Context, arg SetProjectEnabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProjectEnabled, arg.ID, arg.Enabled)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProject = `-- name: UpdateProject :execrows
UPDATE app.projects
SET name = $2, repository_mode = $3, repository_url = NULLIF($4, ''), local_repository_path = NULLIF($5, ''),
    default_branch = $6, configuration = $7::jsonb, updated_at = now()
WHERE id = $1
`

type UpdateProjectParams struct {
	ID             string
	Name           string
	RepositoryMode string
	Column4        interface{}
	Column5        interface{}
	DefaultBranch  string
	Column7        []byte
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.RepositoryMode,
		arg.Column4,
		arg.Column5,
		arg.DefaultBranch,
		arg.Column7,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertIssue = `-- name: UpsertIssue :exec
INSERT INTO app.issues(id, project_id, provider, external_id, display_number, title, body, url, state, labels, priority, eligible, external_created_at, external_updated_at, last_synced_at, raw_snapshot)
VALUES ($1, $2, 'github', $3, $3, $4, $5, $6, $7, $8::jsonb, $9, $10, $11, $12, now(), $13::jsonb)
ON CONFLICT(project_id, provider, external_id) DO UPDATE SET
  display_number = EXCLUDED.display_number,
  title = EXCLUDED.title,
  body = EXCLUDED.body,
  url = EXCLUDED.url,
  state = EXCLUDED.state,
  labels = EXCLUDED.labels,
  priority = EXCLUDED.priority,
  eligible = EXCLUDED.eligible,
  external_created_at = EXCLUDED.external_created_at,
  external_updated_at = EXCLUDED.external_updated_at,
  last_synced_at = now(),
  raw_snapshot = EXCLUDED.raw_snapshot
WHERE
  app.issues.display_number IS DISTINCT FROM EXCLUDED.display_number OR
  app.issues.title IS DISTINCT FROM EXCLUDED.title OR
  app.issues.body IS DISTINCT FROM EXCLUDED.body OR
  app.issues.url IS DISTINCT FROM EXCLUDED.url OR
  app.issues.state IS DISTINCT FROM EXCLUDED.state OR
  app.issues.labels IS DISTINCT FROM EXCLUDED.labels OR
  app.issues.priority IS DISTINCT FROM EXCLUDED.priority OR
  app.issues.eligible IS DISTINCT FROM EXCLUDED.eligible OR
  app.issues.external_created_at IS DISTINCT FROM EXCLUDED.external_created_at OR
  app.issues.external_updated_at IS DISTINCT FROM EXCLUDED.external_updated_at OR
  app.issues.raw_snapshot IS DISTINCT FROM EXCLUDED.raw_snapshot
`

type UpsertIssueParams struct {
	ID                string
	ProjectID         string
	ExternalID        string
	Title             string
	Body              string
	Url               string
	State             string
	Column8           []byte
	Priority          int32
	Eligible          bool
	ExternalCreatedAt pgtype.Timestamptz
	ExternalUpdatedAt pgtype.Timestamptz
	Column13          []byte
}

// eligible is written unconditionally from the tracker's labels (see
// issuePriority) on every sync, full stop -- it is not the scheduler's
// candidate signal by itself any more (see ListQueueEntries and
// ClaimSchedulableIssue's app.workflow_runs.superseded_at join for that), so
// there is no lifecycle state left here for a sync to clobber. See #268 and
// migration 023 for why a CASE guarding this used to live here.
//
// state is now written from what GitHub itself reports (ListIssues fetches
// --state all, not just open) rather than being hardcoded to 'open': every
// scheduling query (ListQueueEntries, GetSchedulerSnapshot,
// ClaimSchedulableIssue) already filters on i.state = 'open', so an issue
// closed on the tracker stops being schedulable the moment this reconciles
// it, with no separate lifecycle write required. The caller also ANDs
// eligible with "still open on the tracker", so a closed issue is reported
// ineligible too, not just excluded via state.
// The DO UPDATE's WHERE guard (added for #290) is what keeps a steady-state
// sync pass -- nothing changed on the tracker since the last one -- from
// rewriting every issue row, full raw_snapshot JSONB included, on every
// single pass. Without it, Postgres has no way to know the SET list would
// produce an identical row and pays a full tuple write (and a fresh xmin,
// and a dead tuple for autovacuum to reclaim) regardless. The comparison
// covers every column the SET list actually writes from EXCLUDED except
// last_synced_at itself (which always advances and would otherwise defeat
// the guard by always differing); a row with no other change simply keeps
// its previous last_synced_at rather than that column alone forcing a write.
func (q *Queries) UpsertIssue(ctx context.Context, arg UpsertIssueParams) error {
	_, err := q.db.Exec(ctx, upsertIssue,
		arg.ID,
		arg.ProjectID,
		arg.ExternalID,
		arg.Title,
		arg.Body,
		arg.Url,
		arg.State,
		arg.Column8,
		arg.Priority,
		arg.Eligible,
		arg.ExternalCreatedAt,
		arg.ExternalUpdatedAt,
		arg.Column13,
	)
	return err
}

const upsertIssueSyncStateFailure = `-- name: UpsertIssueSyncStateFailure :exec
INSERT INTO app.issue_sync_state(project_id, consecutive_failures, next_retry_at, last_error, updated_at)
VALUES ($1, 1, now() + LEAST(INTERVAL '1 minute' * POWER(2, LEAST(1, 10)), INTERVAL '1 hour'), $2, now())
ON CONFLICT(project_id) DO UPDATE SET
  consecutive_failures = app.issue_sync_state.consecutive_failures + 1,
  next_retry_at = now() + LEAST(INTERVAL '1 minute' * POWER(2, LEAST(app.issue_sync_state.consecutive_failures + 1, 10)), INTERVAL '1 hour'),
  last_error = EXCLUDED.last_error,
  updated_at = now()
`

type UpsertIssueSyncStateFailureParams struct {
	ProjectID string
	LastError pgtype.Text
}

// next_retry_at backs off exponentially with consecutive_failures (1 minute,
// 2, 4, 8, ...), capped at 1 hour. The exponent itself is capped (via the
// inner LEAST) before POWER ever sees it, rather than relying on the outer
// LEAST against '1 hour' alone: POWER(2, n) is evaluated first, and an
// uncapped n for a project that has been failing for days would overflow
// double precision (and then interval multiplication) before that outer
// LEAST ever got a chance to clamp the result.
func (q *Queries) UpsertIssueSyncStateFailure(ctx context.Context, arg UpsertIssueSyncStateFailureParams) error {
	_, err := q.db.Exec(ctx, upsertIssueSyncStateFailure, arg.ProjectID, arg.LastError)
	return err
}

const upsertIssueSyncStateSuccess = `-- name: UpsertIssueSyncStateSuccess :exec
INSERT INTO app.issue_sync_state(project_id, consecutive_failures, next_retry_at, last_error, last_synced_at, updated_at)
VALUES ($1, 0, NULL, NULL, now(), now())
ON CONFLICT(project_id) DO UPDATE SET
  consecutive_failures = 0,
  next_retry_at = NULL,
  last_error = NULL,
  last_synced_at = now(),
  updated_at = now()
`

// next_retry_at is reset to NULL on success: leaving a stale future timestamp
// around after a project recovers would keep ListProjectsDueForSync skipping
// it long after there is anything to back off from.
func (q *Queries) UpsertIssueSyncStateSuccess(ctx context.Context, projectID string) error {
	_, err := q.db.Exec(ctx, upsertIssueSyncStateSuccess, projectID)
	return err
}
