// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: server_workflows.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelWorkflowExecutionRequests = `-- name: CancelWorkflowExecutionRequests :exec
UPDATE app.workflow_execution_requests SET status = 'cancelled'
WHERE workflow_run_id = $1 AND status IN ('queued','dispatched')
`

func (q *Queries) CancelWorkflowExecutionRequests(ctx context.Context, workflowRunID string) error {
	_, err := q.db.Exec(ctx, cancelWorkflowExecutionRequests, workflowRunID)
	return err
}

const cancelWorkflowJobOffers = `-- name: CancelWorkflowJobOffers :exec
UPDATE app.job_offers SET status = 'cancelled', responded_at = now()
WHERE status = 'offered' AND job_id IN (SELECT id FROM app.jobs WHERE workflow_run_id = $1)
`

func (q *Queries) CancelWorkflowJobOffers(ctx context.Context, workflowRunID string) error {
	_, err := q.db.Exec(ctx, cancelWorkflowJobOffers, workflowRunID)
	return err
}

const cancelWorkflowJobs = `-- name: CancelWorkflowJobs :one
UPDATE app.jobs SET status = 'cancelled', finished_at = now(), lease_generation = lease_generation + 1, recovery_reason = $2
WHERE workflow_run_id = $1 AND status IN ('offered','preparing','running')
RETURNING id::text AS id, runner_id::text AS runner_id, lease_generation - 1 AS previous_lease_generation
`

type CancelWorkflowJobsParams struct {
	WorkflowRunID  string
	RecoveryReason pgtype.Text
}

type CancelWorkflowJobsRow struct {
	ID                      string
	RunnerID                string
	PreviousLeaseGeneration int32
}

func (q *Queries) CancelWorkflowJobs(ctx context.Context, arg CancelWorkflowJobsParams) (CancelWorkflowJobsRow, error) {
	row := q.db.QueryRow(ctx, cancelWorkflowJobs, arg.WorkflowRunID, arg.RecoveryReason)
	var i CancelWorkflowJobsRow
	err := row.Scan(&i.ID, &i.RunnerID, &i.PreviousLeaseGeneration)
	return i, err
}

const createRetryEvent = `-- name: CreateRetryEvent :exec
INSERT INTO app.workflow_events(workflow_run_id, event_type, severity, payload)
VALUES ($1, 'workflow_transition', 'info', '{"reason":"reopened by manual retry"}'::jsonb)
`

func (q *Queries) CreateRetryEvent(ctx context.Context, workflowRunID string) error {
	_, err := q.db.Exec(ctx, createRetryEvent, workflowRunID)
	return err
}

const getWorkflowDetail = `-- name: GetWorkflowDetail :one
SELECT wr.id::text AS id, wr.project_id::text AS project_id, wr.status, wr.current_phase,
       i.external_id, i.title, wr.branch_name,
       pr.external_id AS pr_external_id, wr.pull_request_external_id AS run_pull_request_external_id,
       pr.url AS pr_url, wr.pull_request_url AS run_pull_request_url,
       pr.state AS pull_request_state, wr.blocking_reason,
       wr.planning_attempts, wr.implementation_attempts, wr.pipeline_repair_attempts, wr.ci_repair_attempts,
       wr.review_cycles, wr.total_agent_executions, wr.created_at, wr.updated_at
FROM app.workflow_runs wr
JOIN app.issues i ON i.id = wr.issue_id
LEFT JOIN app.pull_requests pr ON pr.workflow_run_id = wr.id
WHERE wr.id = $1
`

type GetWorkflowDetailRow struct {
	ID                       string
	ProjectID                string
	Status                   string
	CurrentPhase             string
	ExternalID               string
	Title                    string
	BranchName               pgtype.Text
	PrExternalID             pgtype.Text
	RunPullRequestExternalID pgtype.Text
	PrUrl                    pgtype.Text
	RunPullRequestUrl        pgtype.Text
	PullRequestState         pgtype.Text
	BlockingReason           pgtype.Text
	PlanningAttempts         int32
	ImplementationAttempts   int32
	PipelineRepairAttempts   int32
	CiRepairAttempts         int32
	ReviewCycles             int32
	TotalAgentExecutions     int32
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
}

// pr.external_id/pr.url and wr.pull_request_external_id/wr.pull_request_url are
// combined in Go rather than with SQL COALESCE: sqlc's nullability inference
// does not reliably propagate through COALESCE of two nullable columns (one
// from an outer join), and mistyping either side NOT NULL would panic the
// very first workflow scanned before a pull request exists.
func (q *Queries) GetWorkflowDetail(ctx context.Context, id string) (GetWorkflowDetailRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowDetail, id)
	var i GetWorkflowDetailRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.CurrentPhase,
		&i.ExternalID,
		&i.Title,
		&i.BranchName,
		&i.PrExternalID,
		&i.RunPullRequestExternalID,
		&i.PrUrl,
		&i.RunPullRequestUrl,
		&i.PullRequestState,
		&i.BlockingReason,
		&i.PlanningAttempts,
		&i.ImplementationAttempts,
		&i.PipelineRepairAttempts,
		&i.CiRepairAttempts,
		&i.ReviewCycles,
		&i.TotalAgentExecutions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowForControl = `-- name: GetWorkflowForControl :one
SELECT project_id::text AS project_id, status
FROM app.workflow_runs
WHERE id = $1
FOR UPDATE
`

type GetWorkflowForControlRow struct {
	ProjectID string
	Status    string
}

func (q *Queries) GetWorkflowForControl(ctx context.Context, id string) (GetWorkflowForControlRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowForControl, id)
	var i GetWorkflowForControlRow
	err := row.Scan(&i.ProjectID, &i.Status)
	return i, err
}

const listWorkflowEvents = `-- name: ListWorkflowEvents :many
SELECT id::text AS id, event_type, created_at, payload::text AS payload
FROM app.workflow_events
WHERE workflow_run_id = $1 AND id > $2
ORDER BY id
LIMIT $3
`

type ListWorkflowEventsParams struct {
	WorkflowRunID string
	ID            int64
	Limit         int32
}

type ListWorkflowEventsRow struct {
	ID        string
	EventType string
	CreatedAt pgtype.Timestamptz
	Payload   string
}

func (q *Queries) ListWorkflowEvents(ctx context.Context, arg ListWorkflowEventsParams) ([]ListWorkflowEventsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowEvents, arg.WorkflowRunID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowEventsRow
	for rows.Next() {
		var i ListWorkflowEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.CreatedAt,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowsPage = `-- name: ListWorkflowsPage :many
SELECT wr.id::text AS id, wr.project_id::text AS project_id, wr.status, wr.current_phase,
       i.external_id, i.title, wr.branch_name,
       pr.external_id AS pr_external_id, wr.pull_request_external_id AS run_pull_request_external_id,
       pr.url AS pr_url, wr.pull_request_url AS run_pull_request_url,
       pr.state AS pull_request_state, wr.blocking_reason,
       wr.planning_attempts, wr.implementation_attempts, wr.pipeline_repair_attempts, wr.ci_repair_attempts,
       wr.review_cycles, wr.total_agent_executions, wr.created_at, wr.updated_at
FROM app.workflow_runs wr
JOIN app.issues i ON i.id = wr.issue_id
LEFT JOIN app.pull_requests pr ON pr.workflow_run_id = wr.id
ORDER BY wr.created_at DESC, wr.id
LIMIT $1
`

type ListWorkflowsPageRow struct {
	ID                       string
	ProjectID                string
	Status                   string
	CurrentPhase             string
	ExternalID               string
	Title                    string
	BranchName               pgtype.Text
	PrExternalID             pgtype.Text
	RunPullRequestExternalID pgtype.Text
	PrUrl                    pgtype.Text
	RunPullRequestUrl        pgtype.Text
	PullRequestState         pgtype.Text
	BlockingReason           pgtype.Text
	PlanningAttempts         int32
	ImplementationAttempts   int32
	PipelineRepairAttempts   int32
	CiRepairAttempts         int32
	ReviewCycles             int32
	TotalAgentExecutions     int32
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
}

// Replaces the old ListWorkflowIDs + one GetWorkflowDetail per row: that shape
// was O(all workflow runs) in both rows and queries, and app.workflow_runs
// only grows. This does the same join GetWorkflowDetail does, once, for the
// most recent $1 rows -- see the pr.external_id/wr.pull_request_external_id
// comment on GetWorkflowDetail below for why those aren't COALESCEd in SQL.
func (q *Queries) ListWorkflowsPage(ctx context.Context, limit int32) ([]ListWorkflowsPageRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowsPage, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowsPageRow
	for rows.Next() {
		var i ListWorkflowsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Status,
			&i.CurrentPhase,
			&i.ExternalID,
			&i.Title,
			&i.BranchName,
			&i.PrExternalID,
			&i.RunPullRequestExternalID,
			&i.PrUrl,
			&i.RunPullRequestUrl,
			&i.PullRequestState,
			&i.BlockingReason,
			&i.PlanningAttempts,
			&i.ImplementationAttempts,
			&i.PipelineRepairAttempts,
			&i.CiRepairAttempts,
			&i.ReviewCycles,
			&i.TotalAgentExecutions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenIssueForRetry = `-- name: ReopenIssueForRetry :exec
UPDATE app.issues SET eligible = true
WHERE app.issues.id = (SELECT wr.issue_id FROM app.workflow_runs wr WHERE wr.id = $1) AND state = 'open'
`

func (q *Queries) ReopenIssueForRetry(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, reopenIssueForRetry, id)
	return err
}

const setWorkflowControlStatus = `-- name: SetWorkflowControlStatus :exec
UPDATE app.workflow_runs SET
  status = $2,
  current_phase = $2,
  blocking_reason = CASE WHEN $2 = 'blocked' THEN $3 ELSE blocking_reason END,
  terminal_reason = $3,
  completed_at = now(),
  updated_at = now()
WHERE id = $1
`

type SetWorkflowControlStatusParams struct {
	ID             string
	Status         string
	TerminalReason pgtype.Text
}

func (q *Queries) SetWorkflowControlStatus(ctx context.Context, arg SetWorkflowControlStatusParams) error {
	_, err := q.db.Exec(ctx, setWorkflowControlStatus, arg.ID, arg.Status, arg.TerminalReason)
	return err
}
