// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: server_auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM app.users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminUser = `-- name: CreateAdminUser :exec
INSERT INTO app.users(id, username, password_hash, role)
VALUES ($1, $2, $3, 'admin')
ON CONFLICT(username) DO NOTHING
`

type CreateAdminUserParams struct {
	ID           string
	Username     string
	PasswordHash string
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) error {
	_, err := q.db.Exec(ctx, createAdminUser, arg.ID, arg.Username, arg.PasswordHash)
	return err
}

const createAuditEvent = `-- name: CreateAuditEvent :exec
INSERT INTO app.audit_events(actor_type, actor_id, action, target_type, target_id)
VALUES ('user', $1, $2, $3, $4)
`

type CreateAuditEventParams struct {
	ActorID    pgtype.Text
	Action     string
	TargetType string
	TargetID   string
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.Exec(ctx, createAuditEvent,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
	)
	return err
}

const createUserSession = `-- name: CreateUserSession :exec
INSERT INTO app.user_sessions(id, user_id, token_hash, csrf_token_hash, expires_at, last_seen_at)
VALUES ($1, $2, $3, $4, $5, now())
`

type CreateUserSessionParams struct {
	ID            string
	UserID        string
	TokenHash     string
	CsrfTokenHash string
	ExpiresAt     pgtype.Timestamptz
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) error {
	_, err := q.db.Exec(ctx, createUserSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.CsrfTokenHash,
		arg.ExpiresAt,
	)
	return err
}

const getRunnerCredentialHash = `-- name: GetRunnerCredentialHash :one
SELECT c.credential_hash
FROM app.runners r
JOIN app.runner_credentials c ON c.runner_id = r.id
WHERE r.id = $1 AND r.enabled AND r.revoked_at IS NULL AND c.revoked_at IS NULL
  AND (c.expires_at IS NULL OR c.expires_at > now())
ORDER BY c.created_at DESC
LIMIT 1
`

func (q *Queries) GetRunnerCredentialHash(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getRunnerCredentialHash, id)
	var credential_hash string
	err := row.Scan(&credential_hash)
	return credential_hash, err
}

const getSessionActor = `-- name: GetSessionActor :one
SELECT u.id::text AS id, u.role, us.csrf_token_hash
FROM app.user_sessions us
JOIN app.users u ON u.id = us.user_id
WHERE us.token_hash = $1 AND us.revoked_at IS NULL AND us.expires_at > now() AND u.enabled
`

type GetSessionActorRow struct {
	ID            string
	Role          string
	CsrfTokenHash string
}

func (q *Queries) GetSessionActor(ctx context.Context, tokenHash string) (GetSessionActorRow, error) {
	row := q.db.QueryRow(ctx, getSessionActor, tokenHash)
	var i GetSessionActorRow
	err := row.Scan(&i.ID, &i.Role, &i.CsrfTokenHash)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id::text AS id, password_hash, enabled
FROM app.users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID           string
	PasswordHash string
	Enabled      bool
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(&i.ID, &i.PasswordHash, &i.Enabled)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT username, email, display_name
FROM app.users
WHERE id = $1
`

type GetUserProfileRow struct {
	Username    string
	Email       string
	DisplayName string
}

func (q *Queries) GetUserProfile(ctx context.Context, id string) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, id)
	var i GetUserProfileRow
	err := row.Scan(&i.Username, &i.Email, &i.DisplayName)
	return i, err
}

const revokeSessionByTokens = `-- name: RevokeSessionByTokens :execrows
UPDATE app.user_sessions
SET revoked_at = now()
WHERE token_hash = $1 AND csrf_token_hash = $2 AND revoked_at IS NULL AND expires_at > now()
`

type RevokeSessionByTokensParams struct {
	TokenHash     string
	CsrfTokenHash string
}

func (q *Queries) RevokeSessionByTokens(ctx context.Context, arg RevokeSessionByTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionByTokens, arg.TokenHash, arg.CsrfTokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertSeedRunnerRegistrationToken = `-- name: UpsertSeedRunnerRegistrationToken :exec
INSERT INTO app.runner_registration_tokens(id, token_hash, allowed_labels, expires_at)
VALUES ($1, $2, $3::jsonb, now() + interval '15 minutes')
ON CONFLICT(token_hash) DO UPDATE SET
  allowed_labels = EXCLUDED.allowed_labels,
  expires_at = EXCLUDED.expires_at
WHERE app.runner_registration_tokens.used_at IS NULL
`

type UpsertSeedRunnerRegistrationTokenParams struct {
	ID        string
	TokenHash string
	Column3   []byte
}

func (q *Queries) UpsertSeedRunnerRegistrationToken(ctx context.Context, arg UpsertSeedRunnerRegistrationTokenParams) error {
	_, err := q.db.Exec(ctx, upsertSeedRunnerRegistrationToken, arg.ID, arg.TokenHash, arg.Column3)
	return err
}
