// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: server_scheduler.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptJob = `-- name: AcceptJob :one
UPDATE app.jobs SET status = 'preparing', accepted_at = now(), lease_expires_at = now() + $1::interval
WHERE id = $2 AND runner_id = $3::uuid AND status = 'offered'
RETURNING lease_generation, lease_expires_at
`

type AcceptJobParams struct {
	LeaseDuration pgtype.Interval
	ID            string
	RunnerID      string
}

type AcceptJobRow struct {
	LeaseGeneration int64
	LeaseExpiresAt  pgtype.Timestamptz
}

func (q *Queries) AcceptJob(ctx context.Context, arg AcceptJobParams) (AcceptJobRow, error) {
	row := q.db.QueryRow(ctx, acceptJob, arg.LeaseDuration, arg.ID, arg.RunnerID)
	var i AcceptJobRow
	err := row.Scan(&i.LeaseGeneration, &i.LeaseExpiresAt)
	return i, err
}

const acceptJobOffer = `-- name: AcceptJobOffer :one

UPDATE app.job_offers SET status = 'accepted', responded_at = now()
WHERE job_id = $1 AND runner_id = $2 AND status = 'offered' AND expires_at > now()
RETURNING id::text AS id
`

type AcceptJobOfferParams struct {
	JobID    string
	RunnerID string
}

// DeleteProjectLock lives in delivery.sql (identical statement, already
// generated there); reused as-is rather than duplicated.
func (q *Queries) AcceptJobOffer(ctx context.Context, arg AcceptJobOfferParams) (string, error) {
	row := q.db.QueryRow(ctx, acceptJobOffer, arg.JobID, arg.RunnerID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const cancelJob = `-- name: CancelJob :exec
UPDATE app.jobs SET status = 'cancelled', finished_at = now(), recovery_reason = NULLIF($2, '')
WHERE id = $1
`

type CancelJobParams struct {
	ID      string
	Column2 interface{}
}

func (q *Queries) CancelJob(ctx context.Context, arg CancelJobParams) error {
	_, err := q.db.Exec(ctx, cancelJob, arg.ID, arg.Column2)
	return err
}

const cancelJobOfferByJob = `-- name: CancelJobOfferByJob :exec
UPDATE app.job_offers SET status = 'cancelled', responded_at = now()
WHERE job_id = $1 AND status = 'offered'
`

func (q *Queries) CancelJobOfferByJob(ctx context.Context, jobID string) error {
	_, err := q.db.Exec(ctx, cancelJobOfferByJob, jobID)
	return err
}

const cancelJobOfferByRunner = `-- name: CancelJobOfferByRunner :exec
UPDATE app.job_offers SET status = 'rejected', responded_at = now()
WHERE job_id = $1 AND runner_id = $2
`

type CancelJobOfferByRunnerParams struct {
	JobID    string
	RunnerID string
}

func (q *Queries) CancelJobOfferByRunner(ctx context.Context, arg CancelJobOfferByRunnerParams) error {
	_, err := q.db.Exec(ctx, cancelJobOfferByRunner, arg.JobID, arg.RunnerID)
	return err
}

const cancelOfferedJob = `-- name: CancelOfferedJob :exec
UPDATE app.jobs SET status = 'cancelled', finished_at = now(), recovery_reason = $2
WHERE id = $1 AND status = 'offered'
`

type CancelOfferedJobParams struct {
	ID             string
	RecoveryReason pgtype.Text
}

func (q *Queries) CancelOfferedJob(ctx context.Context, arg CancelOfferedJobParams) error {
	_, err := q.db.Exec(ctx, cancelOfferedJob, arg.ID, arg.RecoveryReason)
	return err
}

const cancelWorkflowRunOfferRejected = `-- name: CancelWorkflowRunOfferRejected :exec
UPDATE app.workflow_runs SET status = 'cancelled', current_phase = 'cancelled', terminal_reason = 'runner rejected offer', completed_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) CancelWorkflowRunOfferRejected(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, cancelWorkflowRunOfferRejected, id)
	return err
}

const cancelWorkflowRunUndelivered = `-- name: CancelWorkflowRunUndelivered :exec
UPDATE app.workflow_runs SET status = 'cancelled', current_phase = 'cancelled', completed_at = now(), terminal_reason = $2
WHERE id = $1
`

type CancelWorkflowRunUndeliveredParams struct {
	ID             string
	TerminalReason pgtype.Text
}

func (q *Queries) CancelWorkflowRunUndelivered(ctx context.Context, arg CancelWorkflowRunUndeliveredParams) error {
	_, err := q.db.Exec(ctx, cancelWorkflowRunUndelivered, arg.ID, arg.TerminalReason)
	return err
}

const claimSchedulableIssue = `-- name: ClaimSchedulableIssue :one
SELECT i.id::text AS issue_id, i.external_id, i.title, i.body,
       p.id::text AS project_id, p.repository_mode, p.repository_url, p.local_repository_path, p.default_branch, p.configuration::text AS configuration,
       r.id::text AS runner_id
FROM app.issues i
JOIN app.projects p ON p.id = i.project_id
JOIN app.runners r ON r.status = 'online' AND r.enabled AND NOT r.draining AND r.revoked_at IS NULL
WHERE i.eligible AND i.state = 'open' AND p.enabled
  AND r.id::text = ANY($1::text[])
  AND r.labels @> COALESCE(p.configuration->'required_runner_labels', '[]'::jsonb)
  AND NOT EXISTS (SELECT 1 FROM app.project_locks l WHERE l.project_id = p.id)
  AND (SELECT COUNT(*) FROM app.jobs j WHERE j.runner_id = r.id AND j.status IN ('offered','preparing','running')) < r.capacity
  AND NOT EXISTS (
    SELECT 1 FROM app.workflow_runs w
    WHERE w.issue_id = i.id AND w.superseded_at IS NULL AND w.status IN ('failed', 'blocked', 'completed')
  )
ORDER BY i.priority DESC, i.external_created_at, i.last_synced_at, i.project_id, i.external_id, r.id
FOR UPDATE OF i, r SKIP LOCKED
LIMIT 1
`

type ClaimSchedulableIssueRow struct {
	IssueID             string
	ExternalID          string
	Title               string
	Body                string
	ProjectID           string
	RepositoryMode      string
	RepositoryUrl       pgtype.Text
	LocalRepositoryPath pgtype.Text
	DefaultBranch       string
	Configuration       string
	RunnerID            string
}

// A runner's in-flight job count is compared against its own registered
// capacity (app.runners.capacity, see migration 003) rather than excluding it
// the instant it holds any job at all: that used to hard-cap every runner at
// one concurrent execution regardless of what it advertised at registration.
// The count is still scoped to this runner (j.runner_id = r.id) so it says
// nothing about any other runner's load, and FOR UPDATE OF i, r still locks
// exactly the issue and runner rows a concurrent ClaimSchedulableIssue would
// also need, so SKIP LOCKED continues to hand a racing caller a different
// issue/runner pair instead of double-booking this one.
func (q *Queries) ClaimSchedulableIssue(ctx context.Context, runnerIds []string) (ClaimSchedulableIssueRow, error) {
	row := q.db.QueryRow(ctx, claimSchedulableIssue, runnerIds)
	var i ClaimSchedulableIssueRow
	err := row.Scan(
		&i.IssueID,
		&i.ExternalID,
		&i.Title,
		&i.Body,
		&i.ProjectID,
		&i.RepositoryMode,
		&i.RepositoryUrl,
		&i.LocalRepositoryPath,
		&i.DefaultBranch,
		&i.Configuration,
		&i.RunnerID,
	)
	return i, err
}

const createJob = `-- name: CreateJob :exec
INSERT INTO app.jobs(id, workflow_run_id, project_id, runner_id, status, lease_generation, offered_at)
VALUES ($1, $2, $3, $4::uuid, 'offered', 1, now())
`

type CreateJobParams struct {
	ID            string
	WorkflowRunID string
	ProjectID     string
	RunnerID      string
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) error {
	_, err := q.db.Exec(ctx, createJob,
		arg.ID,
		arg.WorkflowRunID,
		arg.ProjectID,
		arg.RunnerID,
	)
	return err
}

const createJobOffer = `-- name: CreateJobOffer :exec
INSERT INTO app.job_offers(id, job_id, runner_id, status, expires_at)
VALUES ($1, $2, $3, 'offered', 'infinity')
`

type CreateJobOfferParams struct {
	ID       string
	JobID    string
	RunnerID string
}

func (q *Queries) CreateJobOffer(ctx context.Context, arg CreateJobOfferParams) error {
	_, err := q.db.Exec(ctx, createJobOffer, arg.ID, arg.JobID, arg.RunnerID)
	return err
}

const createProjectLock = `-- name: CreateProjectLock :execrows
INSERT INTO app.project_locks(project_id, workflow_run_id)
VALUES ($1, $2)
ON CONFLICT(project_id) DO NOTHING
`

type CreateProjectLockParams struct {
	ProjectID     string
	WorkflowRunID string
}

func (q *Queries) CreateProjectLock(ctx context.Context, arg CreateProjectLockParams) (int64, error) {
	result, err := q.db.Exec(ctx, createProjectLock, arg.ProjectID, arg.WorkflowRunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createWorkflowEvent = `-- name: CreateWorkflowEvent :exec
INSERT INTO app.workflow_events (workflow_run_id, event_type, severity, payload)
VALUES ($1, $2, $3, $4::jsonb)
`

type CreateWorkflowEventParams struct {
	WorkflowRunID string
	EventType     string
	Severity      string
	Column4       []byte
}

func (q *Queries) CreateWorkflowEvent(ctx context.Context, arg CreateWorkflowEventParams) error {
	_, err := q.db.Exec(ctx, createWorkflowEvent,
		arg.WorkflowRunID,
		arg.EventType,
		arg.Severity,
		arg.Column4,
	)
	return err
}

const createWorkflowRun = `-- name: CreateWorkflowRun :exec
INSERT INTO app.workflow_runs(id, project_id, issue_id, thread_id, status, current_phase, branch_name)
VALUES ($1, $2, $3, $4, 'offered', 'offered', $5)
`

type CreateWorkflowRunParams struct {
	ID         string
	ProjectID  string
	IssueID    string
	ThreadID   string
	BranchName pgtype.Text
}

func (q *Queries) CreateWorkflowRun(ctx context.Context, arg CreateWorkflowRunParams) error {
	_, err := q.db.Exec(ctx, createWorkflowRun,
		arg.ID,
		arg.ProjectID,
		arg.IssueID,
		arg.ThreadID,
		arg.BranchName,
	)
	return err
}

const deleteProjectLockByWorkflow = `-- name: DeleteProjectLockByWorkflow :exec
DELETE FROM app.project_locks WHERE workflow_run_id = $1
`

func (q *Queries) DeleteProjectLockByWorkflow(ctx context.Context, workflowRunID string) error {
	_, err := q.db.Exec(ctx, deleteProjectLockByWorkflow, workflowRunID)
	return err
}

const getJobForOfferReject = `-- name: GetJobForOfferReject :one
SELECT j.workflow_run_id::text AS workflow_run_id, j.project_id::text AS project_id
FROM app.jobs j
JOIN app.job_offers o ON o.job_id = j.id
WHERE j.id = $1 AND o.runner_id = $2 AND o.status = 'offered' AND o.expires_at > now()
FOR UPDATE
`

type GetJobForOfferRejectParams struct {
	ID       string
	RunnerID string
}

type GetJobForOfferRejectRow struct {
	WorkflowRunID string
	ProjectID     string
}

func (q *Queries) GetJobForOfferReject(ctx context.Context, arg GetJobForOfferRejectParams) (GetJobForOfferRejectRow, error) {
	row := q.db.QueryRow(ctx, getJobForOfferReject, arg.ID, arg.RunnerID)
	var i GetJobForOfferRejectRow
	err := row.Scan(&i.WorkflowRunID, &i.ProjectID)
	return i, err
}

const getSchedulerSnapshot = `-- name: GetSchedulerSnapshot :one
SELECT
  (SELECT COUNT(*) FROM app.issues i JOIN app.projects p ON p.id = i.project_id
   WHERE p.enabled AND i.eligible AND i.state = 'open' AND NOT EXISTS (
     SELECT 1 FROM app.workflow_runs w
     WHERE w.issue_id = i.id AND w.superseded_at IS NULL AND w.status IN ('failed', 'blocked', 'completed')
   )) AS queue_depth,
  (SELECT COUNT(*) FROM app.workflow_runs WHERE status NOT IN ('completed','failed','blocked','cancelled')) AS active_workflows,
  (SELECT COUNT(*) FROM app.jobs WHERE status IN ('offered','preparing','running')) AS scheduled_jobs,
  (SELECT COUNT(*) FROM app.runners WHERE enabled AND revoked_at IS NULL) AS enabled_runners,
  hb.oldest_heartbeat::timestamptz AS oldest_heartbeat,
  now()::timestamptz AS db_now
FROM (SELECT 1) AS one
LEFT JOIN LATERAL (
  SELECT MIN(COALESCE(last_seen_at, registered_at)) AS oldest_heartbeat
  FROM app.runners
  WHERE enabled AND revoked_at IS NULL
  HAVING COUNT(*) > 0
) hb ON true
`

type GetSchedulerSnapshotRow struct {
	QueueDepth      int64
	ActiveWorkflows int64
	ScheduledJobs   int64
	EnabledRunners  int64
	OldestHeartbeat pgtype.Timestamptz
	DbNow           pgtype.Timestamptz
}

// The oldest heartbeat is returned as a raw timestamp (rather than an
// already-subtracted epoch age) plus the database's own now(), so the
// nullability of "no enabled runner" survives sqlc's type inference as a
// pgtype.Timestamptz.Valid flag instead of silently becoming a NOT NULL
// float64 that panics on a NULL scan -- see the Go call site for the
// subtraction, which still uses only values this same statement read from
// the database's clock.
func (q *Queries) GetSchedulerSnapshot(ctx context.Context) (GetSchedulerSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getSchedulerSnapshot)
	var i GetSchedulerSnapshotRow
	err := row.Scan(
		&i.QueueDepth,
		&i.ActiveWorkflows,
		&i.ScheduledJobs,
		&i.EnabledRunners,
		&i.OldestHeartbeat,
		&i.DbNow,
	)
	return i, err
}

const listQueueEntries = `-- name: ListQueueEntries :many
SELECT p.id::text AS project_id, p.name AS project_name, i.external_id, i.title, i.priority,
       CASE WHEN NOT p.enabled THEN 'project_disabled'
            WHEN EXISTS (SELECT 1 FROM app.project_locks l WHERE l.project_id = p.id) THEN 'project_locked'
            ELSE '' END AS blocked_reason
FROM app.issues i
JOIN app.projects p ON p.id = i.project_id
WHERE i.eligible AND i.state = 'open' AND NOT EXISTS (
  SELECT 1 FROM app.workflow_runs w
  WHERE w.issue_id = i.id AND w.superseded_at IS NULL AND w.status IN ('failed', 'blocked', 'completed')
)
ORDER BY i.priority DESC, i.external_created_at, i.last_synced_at, i.project_id, i.external_id
LIMIT $1
`

type ListQueueEntriesRow struct {
	ProjectID     string
	ProjectName   string
	ExternalID    string
	Title         string
	Priority      int32
	BlockedReason string
}

func (q *Queries) ListQueueEntries(ctx context.Context, limit int32) ([]ListQueueEntriesRow, error) {
	rows, err := q.db.Query(ctx, listQueueEntries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQueueEntriesRow
	for rows.Next() {
		var i ListQueueEntriesRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ProjectName,
			&i.ExternalID,
			&i.Title,
			&i.Priority,
			&i.BlockedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordJobExecutionEvent = `-- name: RecordJobExecutionEvent :one
UPDATE app.jobs SET
  last_event_sequence = $1,
  status = CASE WHEN $2 = 'started' THEN 'running' WHEN $2 IN ('completed','failed','cancelled') THEN $2 ELSE status END,
  started_at = CASE WHEN $2 = 'started' THEN COALESCE(started_at, now()) ELSE started_at END,
  finished_at = CASE WHEN $2 IN ('completed','failed','cancelled') THEN now() ELSE finished_at END
WHERE id = $3 AND runner_id = $4::uuid AND lease_generation = $5 AND status IN ('preparing','running') AND lease_expires_at > now() AND last_event_sequence < $1
RETURNING workflow_run_id::text AS workflow_run_id
`

type RecordJobExecutionEventParams struct {
	EventSequence   int64
	EventType       interface{}
	ID              string
	RunnerID        string
	LeaseGeneration int64
}

func (q *Queries) RecordJobExecutionEvent(ctx context.Context, arg RecordJobExecutionEventParams) (string, error) {
	row := q.db.QueryRow(ctx, recordJobExecutionEvent,
		arg.EventSequence,
		arg.EventType,
		arg.ID,
		arg.RunnerID,
		arg.LeaseGeneration,
	)
	var workflow_run_id string
	err := row.Scan(&workflow_run_id)
	return workflow_run_id, err
}

const renewJobLease = `-- name: RenewJobLease :one
UPDATE app.jobs SET lease_expires_at = $1
WHERE id = $2 AND runner_id = $3::uuid AND lease_generation = $4 AND status IN ('preparing','running') AND lease_expires_at > now()
RETURNING lease_expires_at
`

type RenewJobLeaseParams struct {
	LeaseExpiresAt  pgtype.Timestamptz
	ID              string
	RunnerID        string
	LeaseGeneration int64
}

func (q *Queries) RenewJobLease(ctx context.Context, arg RenewJobLeaseParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, renewJobLease,
		arg.LeaseExpiresAt,
		arg.ID,
		arg.RunnerID,
		arg.LeaseGeneration,
	)
	var lease_expires_at pgtype.Timestamptz
	err := row.Scan(&lease_expires_at)
	return lease_expires_at, err
}

const setWorkflowPreparing = `-- name: SetWorkflowPreparing :exec
UPDATE app.workflow_runs SET status = 'preparing', updated_at = now()
WHERE app.workflow_runs.id = (SELECT j.workflow_run_id FROM app.jobs j WHERE j.id = $1)
  AND status NOT IN ('completed','failed','blocked','cancelled')
`

func (q *Queries) SetWorkflowPreparing(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setWorkflowPreparing, id)
	return err
}

const setWorkflowTerminalStatus = `-- name: SetWorkflowTerminalStatus :exec
UPDATE app.workflow_runs SET
  status = $2,
  current_phase = $2,
  blocking_reason = COALESCE(NULLIF($3, ''), blocking_reason),
  terminal_reason = COALESCE(NULLIF($3, ''), terminal_reason),
  updated_at = now(),
  completed_at = CASE WHEN $2 IN ('completed','failed','blocked','cancelled') THEN now() ELSE completed_at END
WHERE id = $1
`

type SetWorkflowTerminalStatusParams struct {
	ID      string
	Status  string
	Column3 interface{}
}

func (q *Queries) SetWorkflowTerminalStatus(ctx context.Context, arg SetWorkflowTerminalStatusParams) error {
	_, err := q.db.Exec(ctx, setWorkflowTerminalStatus, arg.ID, arg.Status, arg.Column3)
	return err
}
