// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: server_runners.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRunner = `-- name: CreateRunner :exec
INSERT INTO app.runners (id, name, status, version, labels, capacity, last_seen_at)
VALUES ($1, $2, 'offline', '', $3::jsonb, $4, now())
`

type CreateRunnerParams struct {
	ID       string
	Name     string
	Column3  []byte
	Capacity int32
}

func (q *Queries) CreateRunner(ctx context.Context, arg CreateRunnerParams) error {
	_, err := q.db.Exec(ctx, createRunner,
		arg.ID,
		arg.Name,
		arg.Column3,
		arg.Capacity,
	)
	return err
}

const createRunnerCredential = `-- name: CreateRunnerCredential :exec
INSERT INTO app.runner_credentials (id, runner_id, credential_hash)
VALUES ($1, $2, $3)
`

type CreateRunnerCredentialParams struct {
	ID             string
	RunnerID       string
	CredentialHash string
}

func (q *Queries) CreateRunnerCredential(ctx context.Context, arg CreateRunnerCredentialParams) error {
	_, err := q.db.Exec(ctx, createRunnerCredential, arg.ID, arg.RunnerID, arg.CredentialHash)
	return err
}

const drainRunner = `-- name: DrainRunner :execrows
UPDATE app.runners SET draining = true WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) DrainRunner(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, drainRunner, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enableRunner = `-- name: EnableRunner :execrows
UPDATE app.runners SET enabled = true, draining = false WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) EnableRunner(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, enableRunner, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRunner = `-- name: GetRunner :one
SELECT id::text AS id, name, enabled, draining, status, labels::text AS labels, last_seen_at, version
FROM app.runners
WHERE id = $1
`

type GetRunnerRow struct {
	ID         string
	Name       string
	Enabled    bool
	Draining   bool
	Status     string
	Labels     string
	LastSeenAt pgtype.Timestamptz
	Version    string
}

func (q *Queries) GetRunner(ctx context.Context, id string) (GetRunnerRow, error) {
	row := q.db.QueryRow(ctx, getRunner, id)
	var i GetRunnerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Draining,
		&i.Status,
		&i.Labels,
		&i.LastSeenAt,
		&i.Version,
	)
	return i, err
}

const listRunners = `-- name: ListRunners :many
SELECT id::text AS id, name, enabled, draining, status, labels::text AS labels, last_seen_at, version
FROM app.runners
ORDER BY name, id
`

type ListRunnersRow struct {
	ID         string
	Name       string
	Enabled    bool
	Draining   bool
	Status     string
	Labels     string
	LastSeenAt pgtype.Timestamptz
	Version    string
}

func (q *Queries) ListRunners(ctx context.Context) ([]ListRunnersRow, error) {
	rows, err := q.db.Query(ctx, listRunners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunnersRow
	for rows.Next() {
		var i ListRunnersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.Draining,
			&i.Status,
			&i.Labels,
			&i.LastSeenAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRegistrationTokenUsed = `-- name: MarkRegistrationTokenUsed :exec
UPDATE app.runner_registration_tokens SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkRegistrationTokenUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markRegistrationTokenUsed, id)
	return err
}

const recordRunnerHeartbeat = `-- name: RecordRunnerHeartbeat :exec
UPDATE app.runners
SET status = 'online', last_seen_at = now(), version = COALESCE(NULLIF($2, ''), version)
WHERE id = $1 AND enabled AND revoked_at IS NULL
`

type RecordRunnerHeartbeatParams struct {
	ID      string
	Column2 interface{}
}

func (q *Queries) RecordRunnerHeartbeat(ctx context.Context, arg RecordRunnerHeartbeatParams) error {
	_, err := q.db.Exec(ctx, recordRunnerHeartbeat, arg.ID, arg.Column2)
	return err
}

const revokeRunner = `-- name: RevokeRunner :execrows
UPDATE app.runners SET enabled = false, status = 'offline', revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRunner(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRunner, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRunnerCredentials = `-- name: RevokeRunnerCredentials :exec
UPDATE app.runner_credentials SET revoked_at = now() WHERE runner_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRunnerCredentials(ctx context.Context, runnerID string) error {
	_, err := q.db.Exec(ctx, revokeRunnerCredentials, runnerID)
	return err
}

const selectValidRegistrationToken = `-- name: SelectValidRegistrationToken :one
SELECT id::text AS id
FROM app.runner_registration_tokens
WHERE token_hash = $1 AND used_at IS NULL AND revoked_at IS NULL AND expires_at > now() AND allowed_labels @> $2::jsonb
FOR UPDATE
`

type SelectValidRegistrationTokenParams struct {
	TokenHash string
	Column2   []byte
}

func (q *Queries) SelectValidRegistrationToken(ctx context.Context, arg SelectValidRegistrationTokenParams) (string, error) {
	row := q.db.QueryRow(ctx, selectValidRegistrationToken, arg.TokenHash, arg.Column2)
	var id string
	err := row.Scan(&id)
	return id, err
}

const setRunnerDraining = `-- name: SetRunnerDraining :exec
UPDATE app.runners SET draining = $2, last_seen_at = now() WHERE id = $1
`

type SetRunnerDrainingParams struct {
	ID       string
	Draining bool
}

func (q *Queries) SetRunnerDraining(ctx context.Context, arg SetRunnerDrainingParams) error {
	_, err := q.db.Exec(ctx, setRunnerDraining, arg.ID, arg.Draining)
	return err
}
