// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: server_projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProjectIssues = `-- name: CountProjectIssues :one
SELECT COUNT(*) FROM app.issues WHERE project_id = $1
`

func (q *Queries) CountProjectIssues(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectIssues, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :exec
INSERT INTO app.projects (id, name, repository_mode, repository_url, local_repository_path, default_branch, configuration)
VALUES ($1, $2, $3, NULLIF($4, ''), NULLIF($5, ''), $6, $7::jsonb)
`

type CreateProjectParams struct {
	ID             string
	Name           string
	RepositoryMode string
	Column4        interface{}
	Column5        interface{}
	DefaultBranch  string
	Column7        []byte
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.Exec(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.RepositoryMode,
		arg.Column4,
		arg.Column5,
		arg.DefaultBranch,
		arg.Column7,
	)
	return err
}

const createProjectPipelineStep = `-- name: CreateProjectPipelineStep :exec
INSERT INTO app.project_pipeline_steps(id, project_id, position, name, command, timeout_seconds, required)
VALUES ($1, $2, $3, $4, $4, $5, $6)
`

type CreateProjectPipelineStepParams struct {
	ID             string
	ProjectID      string
	Position       int32
	Name           string
	TimeoutSeconds int32
	Required       bool
}

func (q *Queries) CreateProjectPipelineStep(ctx context.Context, arg CreateProjectPipelineStepParams) error {
	_, err := q.db.Exec(ctx, createProjectPipelineStep,
		arg.ID,
		arg.ProjectID,
		arg.Position,
		arg.Name,
		arg.TimeoutSeconds,
		arg.Required,
	)
	return err
}

const deleteProjectPipelineSteps = `-- name: DeleteProjectPipelineSteps :exec
DELETE FROM app.project_pipeline_steps WHERE project_id = $1
`

func (q *Queries) DeleteProjectPipelineSteps(ctx context.Context, projectID string) error {
	_, err := q.db.Exec(ctx, deleteProjectPipelineSteps, projectID)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id::text AS id, name, enabled, repository_mode, repository_url, local_repository_path, default_branch, configuration::text AS configuration
FROM app.projects
WHERE id = $1
`

type GetProjectRow struct {
	ID                  string
	Name                string
	Enabled             bool
	RepositoryMode      string
	RepositoryUrl       pgtype.Text
	LocalRepositoryPath pgtype.Text
	DefaultBranch       string
	Configuration       string
}

func (q *Queries) GetProject(ctx context.Context, id string) (GetProjectRow, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i GetProjectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.RepositoryMode,
		&i.RepositoryUrl,
		&i.LocalRepositoryPath,
		&i.DefaultBranch,
		&i.Configuration,
	)
	return i, err
}

const issueSyncStatusEntries = `-- name: IssueSyncStatusEntries :many
SELECT p.id::text AS id, p.name, p.enabled, COUNT(i.id) AS issue_count,
       COUNT(i.id) FILTER(WHERE i.eligible) AS eligible_count,
       s.last_synced_at, s.consecutive_failures, s.next_retry_at, s.last_error
FROM app.projects p
LEFT JOIN app.issues i ON i.project_id = p.id
LEFT JOIN app.issue_sync_state s ON s.project_id = p.id
GROUP BY p.id, p.name, p.enabled, s.last_synced_at, s.consecutive_failures, s.next_retry_at, s.last_error
ORDER BY p.name, p.id
`

type IssueSyncStatusEntriesRow struct {
	ID                  string
	Name                string
	Enabled             bool
	IssueCount          int64
	EligibleCount       int64
	LastSyncedAt        pgtype.Timestamptz
	ConsecutiveFailures pgtype.Int4
	NextRetryAt         pgtype.Timestamptz
	LastError           pgtype.Text
}

func (q *Queries) IssueSyncStatusEntries(ctx context.Context) ([]IssueSyncStatusEntriesRow, error) {
	rows, err := q.db.Query(ctx, issueSyncStatusEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IssueSyncStatusEntriesRow
	for rows.Next() {
		var i IssueSyncStatusEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.IssueCount,
			&i.EligibleCount,
			&i.LastSyncedAt,
			&i.ConsecutiveFailures,
			&i.NextRetryAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectIDs = `-- name: ListProjectIDs :many
SELECT id::text AS id FROM app.projects ORDER BY name, id
`

func (q *Queries) ListProjectIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listProjectIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectPipelineSteps = `-- name: ListProjectPipelineSteps :many
SELECT command, timeout_seconds, position, required
FROM app.project_pipeline_steps
WHERE project_id = $1
ORDER BY position, id
`

type ListProjectPipelineStepsRow struct {
	Command        string
	TimeoutSeconds int32
	Position       int32
	Required       bool
}

func (q *Queries) ListProjectPipelineSteps(ctx context.Context, projectID string) ([]ListProjectPipelineStepsRow, error) {
	rows, err := q.db.Query(ctx, listProjectPipelineSteps, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectPipelineStepsRow
	for rows.Next() {
		var i ListProjectPipelineStepsRow
		if err := rows.Scan(
			&i.Command,
			&i.TimeoutSeconds,
			&i.Position,
			&i.Required,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncableProjectByID = `-- name: ListSyncableProjectByID :many
SELECT id::text AS id, repository_url
FROM app.projects
WHERE enabled AND id = $1
`

type ListSyncableProjectByIDRow struct {
	ID            string
	RepositoryUrl pgtype.Text
}

func (q *Queries) ListSyncableProjectByID(ctx context.Context, id string) ([]ListSyncableProjectByIDRow, error) {
	rows, err := q.db.Query(ctx, listSyncableProjectByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSyncableProjectByIDRow
	for rows.Next() {
		var i ListSyncableProjectByIDRow
		if err := rows.Scan(&i.ID, &i.RepositoryUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncableProjects = `-- name: ListSyncableProjects :many
SELECT id::text AS id, repository_url
FROM app.projects
WHERE enabled
`

type ListSyncableProjectsRow struct {
	ID            string
	RepositoryUrl pgtype.Text
}

func (q *Queries) ListSyncableProjects(ctx context.Context) ([]ListSyncableProjectsRow, error) {
	rows, err := q.db.Query(ctx, listSyncableProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSyncableProjectsRow
	for rows.Next() {
		var i ListSyncableProjectsRow
		if err := rows.Scan(&i.ID, &i.RepositoryUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectEnabled = `-- name: SetProjectEnabled :execrows
UPDATE app.projects SET enabled = $2, updated_at = now() WHERE id = $1
`

type SetProjectEnabledParams struct {
	ID      string
	Enabled bool
}

func (q *Queries) SetProjectEnabled(ctx context.Context, arg SetProjectEnabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProjectEnabled, arg.ID, arg.Enabled)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProject = `-- name: UpdateProject :execrows
UPDATE app.projects
SET name = $2, repository_mode = $3, repository_url = NULLIF($4, ''), local_repository_path = NULLIF($5, ''),
    default_branch = $6, configuration = $7::jsonb, updated_at = now()
WHERE id = $1
`

type UpdateProjectParams struct {
	ID             string
	Name           string
	RepositoryMode string
	Column4        interface{}
	Column5        interface{}
	DefaultBranch  string
	Column7        []byte
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.RepositoryMode,
		arg.Column4,
		arg.Column5,
		arg.DefaultBranch,
		arg.Column7,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertIssue = `-- name: UpsertIssue :exec
INSERT INTO app.issues(id, project_id, provider, external_id, display_number, title, body, url, state, labels, priority, eligible, external_created_at, external_updated_at, last_synced_at, raw_snapshot)
VALUES ($1, $2, 'github', $3, $3, $4, $5, $6, 'open', $7::jsonb, $8, $9, $10, $11, now(), $12::jsonb)
ON CONFLICT(project_id, provider, external_id) DO UPDATE SET
  display_number = EXCLUDED.display_number,
  title = EXCLUDED.title,
  body = EXCLUDED.body,
  url = EXCLUDED.url,
  state = 'open',
  labels = EXCLUDED.labels,
  priority = EXCLUDED.priority,
  eligible = CASE WHEN EXISTS(SELECT 1 FROM app.workflow_runs w WHERE w.issue_id = app.issues.id) THEN app.issues.eligible ELSE EXCLUDED.eligible END,
  external_created_at = EXCLUDED.external_created_at,
  external_updated_at = EXCLUDED.external_updated_at,
  last_synced_at = now(),
  raw_snapshot = EXCLUDED.raw_snapshot
`

type UpsertIssueParams struct {
	ID                string
	ProjectID         string
	ExternalID        string
	Title             string
	Body              string
	Url               string
	Column7           []byte
	Priority          int32
	Eligible          bool
	ExternalCreatedAt pgtype.Timestamptz
	ExternalUpdatedAt pgtype.Timestamptz
	Column12          []byte
}

func (q *Queries) UpsertIssue(ctx context.Context, arg UpsertIssueParams) error {
	_, err := q.db.Exec(ctx, upsertIssue,
		arg.ID,
		arg.ProjectID,
		arg.ExternalID,
		arg.Title,
		arg.Body,
		arg.Url,
		arg.Column7,
		arg.Priority,
		arg.Eligible,
		arg.ExternalCreatedAt,
		arg.ExternalUpdatedAt,
		arg.Column12,
	)
	return err
}

const upsertIssueSyncStateFailure = `-- name: UpsertIssueSyncStateFailure :exec
INSERT INTO app.issue_sync_state(project_id, consecutive_failures, last_error, updated_at)
VALUES ($1, 1, $2, now())
ON CONFLICT(project_id) DO UPDATE SET
  consecutive_failures = app.issue_sync_state.consecutive_failures + 1,
  last_error = EXCLUDED.last_error,
  updated_at = now()
`

type UpsertIssueSyncStateFailureParams struct {
	ProjectID string
	LastError pgtype.Text
}

func (q *Queries) UpsertIssueSyncStateFailure(ctx context.Context, arg UpsertIssueSyncStateFailureParams) error {
	_, err := q.db.Exec(ctx, upsertIssueSyncStateFailure, arg.ProjectID, arg.LastError)
	return err
}

const upsertIssueSyncStateSuccess = `-- name: UpsertIssueSyncStateSuccess :exec
INSERT INTO app.issue_sync_state(project_id, consecutive_failures, last_error, last_synced_at, updated_at)
VALUES ($1, 0, NULL, now(), now())
ON CONFLICT(project_id) DO UPDATE SET
  consecutive_failures = 0,
  last_error = NULL,
  last_synced_at = now(),
  updated_at = now()
`

func (q *Queries) UpsertIssueSyncStateSuccess(ctx context.Context, projectID string) error {
	_, err := q.db.Exec(ctx, upsertIssueSyncStateSuccess, projectID)
	return err
}
