// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: task_sources.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listProjectTaskSources = `-- name: ListProjectTaskSources :many

SELECT id::text AS id, project_id::text AS project_id, provider, name, enabled, configuration::text AS configuration, created_at, updated_at
FROM app.project_task_sources
WHERE project_id = $1
ORDER BY name, id
`

type ListProjectTaskSourcesRow struct {
	ID            string
	ProjectID     string
	Provider      string
	Name          string
	Enabled       bool
	Configuration string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

// Task sources (#293): the first-class row a project's task sources live
// in, re-keying what used to be app.projects.issue_tracker_type (a single
// scalar, dropped by migration 026) onto app.project_task_sources (1..N per
// project, 0 valid).
//
// Only a read query is defined here for now. Creating, editing, enabling and
// deleting a source needs the field-level descriptor #294 introduces (which
// kind of source needs which configuration fields, and which of them are
// secrets) to have a real write API rather than a hand-rolled one #294 would
// have to redesign around anyway -- see the PR description for #293. Every
// project already has at least its migrated default source from 026, so a
// read-only surface is enough to make what is configured visible.
func (q *Queries) ListProjectTaskSources(ctx context.Context, projectID string) ([]ListProjectTaskSourcesRow, error) {
	rows, err := q.db.Query(ctx, listProjectTaskSources, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectTaskSourcesRow
	for rows.Next() {
		var i ListProjectTaskSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Provider,
			&i.Name,
			&i.Enabled,
			&i.Configuration,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
