# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import control_plane_pb2 as proto_dot_control__plane__pb2


class ControlPlaneStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/loop.control.v1.ControlPlane/Login',
                request_serializer=proto_dot_control__plane__pb2.LoginRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.WhoAmI = channel.unary_unary(
                '/loop.control.v1.ControlPlane/WhoAmI',
                request_serializer=proto_dot_control__plane__pb2.WhoAmIRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.WhoAmIResponse.FromString,
                _registered_method=True)
        self.ListProjects = channel.unary_unary(
                '/loop.control.v1.ControlPlane/ListProjects',
                request_serializer=proto_dot_control__plane__pb2.ListProjectsRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.ListProjectsResponse.FromString,
                _registered_method=True)
        self.CreateProject = channel.unary_unary(
                '/loop.control.v1.ControlPlane/CreateProject',
                request_serializer=proto_dot_control__plane__pb2.CreateProjectRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.CreateProjectResponse.FromString,
                _registered_method=True)
        self.UpdateProject = channel.unary_unary(
                '/loop.control.v1.ControlPlane/UpdateProject',
                request_serializer=proto_dot_control__plane__pb2.UpdateProjectRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.UpdateProjectResponse.FromString,
                _registered_method=True)
        self.SetProjectEnabled = channel.unary_unary(
                '/loop.control.v1.ControlPlane/SetProjectEnabled',
                request_serializer=proto_dot_control__plane__pb2.SetProjectEnabledRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.SetProjectEnabledResponse.FromString,
                _registered_method=True)
        self.CreateRunnerRegistrationToken = channel.unary_unary(
                '/loop.control.v1.ControlPlane/CreateRunnerRegistrationToken',
                request_serializer=proto_dot_control__plane__pb2.CreateRunnerRegistrationTokenRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.CreateRunnerRegistrationTokenResponse.FromString,
                _registered_method=True)
        self.ListRunnerRegistrationTokens = channel.unary_unary(
                '/loop.control.v1.ControlPlane/ListRunnerRegistrationTokens',
                request_serializer=proto_dot_control__plane__pb2.ListRunnerRegistrationTokensRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.ListRunnerRegistrationTokensResponse.FromString,
                _registered_method=True)
        self.RevokeRunnerRegistrationToken = channel.unary_unary(
                '/loop.control.v1.ControlPlane/RevokeRunnerRegistrationToken',
                request_serializer=proto_dot_control__plane__pb2.RevokeRunnerRegistrationTokenRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.RevokeRunnerRegistrationTokenResponse.FromString,
                _registered_method=True)
        self.ListWorkflows = channel.unary_unary(
                '/loop.control.v1.ControlPlane/ListWorkflows',
                request_serializer=proto_dot_control__plane__pb2.ListWorkflowsRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.ListWorkflowsResponse.FromString,
                _registered_method=True)
        self.ListRunners = channel.unary_unary(
                '/loop.control.v1.ControlPlane/ListRunners',
                request_serializer=proto_dot_control__plane__pb2.ListRunnersRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.ListRunnersResponse.FromString,
                _registered_method=True)
        self.SubmitHumanDecision = channel.unary_unary(
                '/loop.control.v1.ControlPlane/SubmitHumanDecision',
                request_serializer=proto_dot_control__plane__pb2.SubmitHumanDecisionRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.SubmitHumanDecisionResponse.FromString,
                _registered_method=True)
        self.GetWorkflow = channel.unary_unary(
                '/loop.control.v1.ControlPlane/GetWorkflow',
                request_serializer=proto_dot_control__plane__pb2.GetWorkflowRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.GetWorkflowResponse.FromString,
                _registered_method=True)
        self.RetryWorkflow = channel.unary_unary(
                '/loop.control.v1.ControlPlane/RetryWorkflow',
                request_serializer=proto_dot_control__plane__pb2.WorkflowActionRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.WorkflowActionResponse.FromString,
                _registered_method=True)
        self.CancelWorkflow = channel.unary_unary(
                '/loop.control.v1.ControlPlane/CancelWorkflow',
                request_serializer=proto_dot_control__plane__pb2.WorkflowActionRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.WorkflowActionResponse.FromString,
                _registered_method=True)
        self.BlockWorkflow = channel.unary_unary(
                '/loop.control.v1.ControlPlane/BlockWorkflow',
                request_serializer=proto_dot_control__plane__pb2.WorkflowActionRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.WorkflowActionResponse.FromString,
                _registered_method=True)
        self.SetRunnerState = channel.unary_unary(
                '/loop.control.v1.ControlPlane/SetRunnerState',
                request_serializer=proto_dot_control__plane__pb2.SetRunnerStateRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.SetRunnerStateResponse.FromString,
                _registered_method=True)
        self.ListQueue = channel.unary_unary(
                '/loop.control.v1.ControlPlane/ListQueue',
                request_serializer=proto_dot_control__plane__pb2.ListQueueRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.ListQueueResponse.FromString,
                _registered_method=True)
        self.SubscribeEvents = channel.unary_stream(
                '/loop.control.v1.ControlPlane/SubscribeEvents',
                request_serializer=proto_dot_control__plane__pb2.SubscribeEventsRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.ControlPlaneEvent.FromString,
                _registered_method=True)


class ControlPlaneServicer:
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WhoAmI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetProjectEnabled(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRunnerRegistrationToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRunnerRegistrationTokens(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeRunnerRegistrationToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkflows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRunners(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitHumanDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetryWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BlockWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRunnerState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlPlaneServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=proto_dot_control__plane__pb2.LoginRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.LoginResponse.SerializeToString,
            ),
            'WhoAmI': grpc.unary_unary_rpc_method_handler(
                    servicer.WhoAmI,
                    request_deserializer=proto_dot_control__plane__pb2.WhoAmIRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.WhoAmIResponse.SerializeToString,
            ),
            'ListProjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProjects,
                    request_deserializer=proto_dot_control__plane__pb2.ListProjectsRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.ListProjectsResponse.SerializeToString,
            ),
            'CreateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProject,
                    request_deserializer=proto_dot_control__plane__pb2.CreateProjectRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.CreateProjectResponse.SerializeToString,
            ),
            'UpdateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProject,
                    request_deserializer=proto_dot_control__plane__pb2.UpdateProjectRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.UpdateProjectResponse.SerializeToString,
            ),
            'SetProjectEnabled': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProjectEnabled,
                    request_deserializer=proto_dot_control__plane__pb2.SetProjectEnabledRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.SetProjectEnabledResponse.SerializeToString,
            ),
            'CreateRunnerRegistrationToken': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRunnerRegistrationToken,
                    request_deserializer=proto_dot_control__plane__pb2.CreateRunnerRegistrationTokenRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.CreateRunnerRegistrationTokenResponse.SerializeToString,
            ),
            'ListRunnerRegistrationTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRunnerRegistrationTokens,
                    request_deserializer=proto_dot_control__plane__pb2.ListRunnerRegistrationTokensRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.ListRunnerRegistrationTokensResponse.SerializeToString,
            ),
            'RevokeRunnerRegistrationToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeRunnerRegistrationToken,
                    request_deserializer=proto_dot_control__plane__pb2.RevokeRunnerRegistrationTokenRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.RevokeRunnerRegistrationTokenResponse.SerializeToString,
            ),
            'ListWorkflows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkflows,
                    request_deserializer=proto_dot_control__plane__pb2.ListWorkflowsRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.ListWorkflowsResponse.SerializeToString,
            ),
            'ListRunners': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRunners,
                    request_deserializer=proto_dot_control__plane__pb2.ListRunnersRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.ListRunnersResponse.SerializeToString,
            ),
            'SubmitHumanDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitHumanDecision,
                    request_deserializer=proto_dot_control__plane__pb2.SubmitHumanDecisionRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.SubmitHumanDecisionResponse.SerializeToString,
            ),
            'GetWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkflow,
                    request_deserializer=proto_dot_control__plane__pb2.GetWorkflowRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.GetWorkflowResponse.SerializeToString,
            ),
            'RetryWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.RetryWorkflow,
                    request_deserializer=proto_dot_control__plane__pb2.WorkflowActionRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.WorkflowActionResponse.SerializeToString,
            ),
            'CancelWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelWorkflow,
                    request_deserializer=proto_dot_control__plane__pb2.WorkflowActionRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.WorkflowActionResponse.SerializeToString,
            ),
            'BlockWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.BlockWorkflow,
                    request_deserializer=proto_dot_control__plane__pb2.WorkflowActionRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.WorkflowActionResponse.SerializeToString,
            ),
            'SetRunnerState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRunnerState,
                    request_deserializer=proto_dot_control__plane__pb2.SetRunnerStateRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.SetRunnerStateResponse.SerializeToString,
            ),
            'ListQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.ListQueue,
                    request_deserializer=proto_dot_control__plane__pb2.ListQueueRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.ListQueueResponse.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=proto_dot_control__plane__pb2.SubscribeEventsRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.ControlPlaneEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loop.control.v1.ControlPlane', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loop.control.v1.ControlPlane', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlPlane:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/Login',
            proto_dot_control__plane__pb2.LoginRequest.SerializeToString,
            proto_dot_control__plane__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WhoAmI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/WhoAmI',
            proto_dot_control__plane__pb2.WhoAmIRequest.SerializeToString,
            proto_dot_control__plane__pb2.WhoAmIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/ListProjects',
            proto_dot_control__plane__pb2.ListProjectsRequest.SerializeToString,
            proto_dot_control__plane__pb2.ListProjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/CreateProject',
            proto_dot_control__plane__pb2.CreateProjectRequest.SerializeToString,
            proto_dot_control__plane__pb2.CreateProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/UpdateProject',
            proto_dot_control__plane__pb2.UpdateProjectRequest.SerializeToString,
            proto_dot_control__plane__pb2.UpdateProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetProjectEnabled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/SetProjectEnabled',
            proto_dot_control__plane__pb2.SetProjectEnabledRequest.SerializeToString,
            proto_dot_control__plane__pb2.SetProjectEnabledResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRunnerRegistrationToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/CreateRunnerRegistrationToken',
            proto_dot_control__plane__pb2.CreateRunnerRegistrationTokenRequest.SerializeToString,
            proto_dot_control__plane__pb2.CreateRunnerRegistrationTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRunnerRegistrationTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/ListRunnerRegistrationTokens',
            proto_dot_control__plane__pb2.ListRunnerRegistrationTokensRequest.SerializeToString,
            proto_dot_control__plane__pb2.ListRunnerRegistrationTokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeRunnerRegistrationToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/RevokeRunnerRegistrationToken',
            proto_dot_control__plane__pb2.RevokeRunnerRegistrationTokenRequest.SerializeToString,
            proto_dot_control__plane__pb2.RevokeRunnerRegistrationTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkflows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/ListWorkflows',
            proto_dot_control__plane__pb2.ListWorkflowsRequest.SerializeToString,
            proto_dot_control__plane__pb2.ListWorkflowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRunners(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/ListRunners',
            proto_dot_control__plane__pb2.ListRunnersRequest.SerializeToString,
            proto_dot_control__plane__pb2.ListRunnersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitHumanDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/SubmitHumanDecision',
            proto_dot_control__plane__pb2.SubmitHumanDecisionRequest.SerializeToString,
            proto_dot_control__plane__pb2.SubmitHumanDecisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/GetWorkflow',
            proto_dot_control__plane__pb2.GetWorkflowRequest.SerializeToString,
            proto_dot_control__plane__pb2.GetWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetryWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/RetryWorkflow',
            proto_dot_control__plane__pb2.WorkflowActionRequest.SerializeToString,
            proto_dot_control__plane__pb2.WorkflowActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/CancelWorkflow',
            proto_dot_control__plane__pb2.WorkflowActionRequest.SerializeToString,
            proto_dot_control__plane__pb2.WorkflowActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BlockWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/BlockWorkflow',
            proto_dot_control__plane__pb2.WorkflowActionRequest.SerializeToString,
            proto_dot_control__plane__pb2.WorkflowActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRunnerState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/SetRunnerState',
            proto_dot_control__plane__pb2.SetRunnerStateRequest.SerializeToString,
            proto_dot_control__plane__pb2.SetRunnerStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/ListQueue',
            proto_dot_control__plane__pb2.ListQueueRequest.SerializeToString,
            proto_dot_control__plane__pb2.ListQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/loop.control.v1.ControlPlane/SubscribeEvents',
            proto_dot_control__plane__pb2.SubscribeEventsRequest.SerializeToString,
            proto_dot_control__plane__pb2.ControlPlaneEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
