# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import control_plane_pb2 as proto_dot_control__plane__pb2


class ControlPlaneStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/loop.control.v1.ControlPlane/Login',
                request_serializer=proto_dot_control__plane__pb2.LoginRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.ListProjects = channel.unary_unary(
                '/loop.control.v1.ControlPlane/ListProjects',
                request_serializer=proto_dot_control__plane__pb2.ListProjectsRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.ListProjectsResponse.FromString,
                _registered_method=True)
        self.CreateProject = channel.unary_unary(
                '/loop.control.v1.ControlPlane/CreateProject',
                request_serializer=proto_dot_control__plane__pb2.CreateProjectRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.CreateProjectResponse.FromString,
                _registered_method=True)
        self.UpdateProject = channel.unary_unary(
                '/loop.control.v1.ControlPlane/UpdateProject',
                request_serializer=proto_dot_control__plane__pb2.UpdateProjectRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.UpdateProjectResponse.FromString,
                _registered_method=True)
        self.SetProjectEnabled = channel.unary_unary(
                '/loop.control.v1.ControlPlane/SetProjectEnabled',
                request_serializer=proto_dot_control__plane__pb2.SetProjectEnabledRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.SetProjectEnabledResponse.FromString,
                _registered_method=True)
        self.CreateRunnerRegistrationToken = channel.unary_unary(
                '/loop.control.v1.ControlPlane/CreateRunnerRegistrationToken',
                request_serializer=proto_dot_control__plane__pb2.CreateRunnerRegistrationTokenRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.CreateRunnerRegistrationTokenResponse.FromString,
                _registered_method=True)
        self.ListRunnerRegistrationTokens = channel.unary_unary(
                '/loop.control.v1.ControlPlane/ListRunnerRegistrationTokens',
                request_serializer=proto_dot_control__plane__pb2.ListRunnerRegistrationTokensRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.ListRunnerRegistrationTokensResponse.FromString,
                _registered_method=True)
        self.RevokeRunnerRegistrationToken = channel.unary_unary(
                '/loop.control.v1.ControlPlane/RevokeRunnerRegistrationToken',
                request_serializer=proto_dot_control__plane__pb2.RevokeRunnerRegistrationTokenRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.RevokeRunnerRegistrationTokenResponse.FromString,
                _registered_method=True)
        self.ListWorkflows = channel.unary_unary(
                '/loop.control.v1.ControlPlane/ListWorkflows',
                request_serializer=proto_dot_control__plane__pb2.ListWorkflowsRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.ListWorkflowsResponse.FromString,
                _registered_method=True)
        self.ListRunners = channel.unary_unary(
                '/loop.control.v1.ControlPlane/ListRunners',
                request_serializer=proto_dot_control__plane__pb2.ListRunnersRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane__pb2.ListRunnersResponse.FromString,
                _registered_method=True)


class ControlPlaneServicer:
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetProjectEnabled(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRunnerRegistrationToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRunnerRegistrationTokens(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeRunnerRegistrationToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkflows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRunners(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlPlaneServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=proto_dot_control__plane__pb2.LoginRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.LoginResponse.SerializeToString,
            ),
            'ListProjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProjects,
                    request_deserializer=proto_dot_control__plane__pb2.ListProjectsRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.ListProjectsResponse.SerializeToString,
            ),
            'CreateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProject,
                    request_deserializer=proto_dot_control__plane__pb2.CreateProjectRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.CreateProjectResponse.SerializeToString,
            ),
            'UpdateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProject,
                    request_deserializer=proto_dot_control__plane__pb2.UpdateProjectRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.UpdateProjectResponse.SerializeToString,
            ),
            'SetProjectEnabled': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProjectEnabled,
                    request_deserializer=proto_dot_control__plane__pb2.SetProjectEnabledRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.SetProjectEnabledResponse.SerializeToString,
            ),
            'CreateRunnerRegistrationToken': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRunnerRegistrationToken,
                    request_deserializer=proto_dot_control__plane__pb2.CreateRunnerRegistrationTokenRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.CreateRunnerRegistrationTokenResponse.SerializeToString,
            ),
            'ListRunnerRegistrationTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRunnerRegistrationTokens,
                    request_deserializer=proto_dot_control__plane__pb2.ListRunnerRegistrationTokensRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.ListRunnerRegistrationTokensResponse.SerializeToString,
            ),
            'RevokeRunnerRegistrationToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeRunnerRegistrationToken,
                    request_deserializer=proto_dot_control__plane__pb2.RevokeRunnerRegistrationTokenRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.RevokeRunnerRegistrationTokenResponse.SerializeToString,
            ),
            'ListWorkflows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkflows,
                    request_deserializer=proto_dot_control__plane__pb2.ListWorkflowsRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.ListWorkflowsResponse.SerializeToString,
            ),
            'ListRunners': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRunners,
                    request_deserializer=proto_dot_control__plane__pb2.ListRunnersRequest.FromString,
                    response_serializer=proto_dot_control__plane__pb2.ListRunnersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loop.control.v1.ControlPlane', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loop.control.v1.ControlPlane', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlPlane:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/Login',
            proto_dot_control__plane__pb2.LoginRequest.SerializeToString,
            proto_dot_control__plane__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/ListProjects',
            proto_dot_control__plane__pb2.ListProjectsRequest.SerializeToString,
            proto_dot_control__plane__pb2.ListProjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/CreateProject',
            proto_dot_control__plane__pb2.CreateProjectRequest.SerializeToString,
            proto_dot_control__plane__pb2.CreateProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/UpdateProject',
            proto_dot_control__plane__pb2.UpdateProjectRequest.SerializeToString,
            proto_dot_control__plane__pb2.UpdateProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetProjectEnabled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/SetProjectEnabled',
            proto_dot_control__plane__pb2.SetProjectEnabledRequest.SerializeToString,
            proto_dot_control__plane__pb2.SetProjectEnabledResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRunnerRegistrationToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/CreateRunnerRegistrationToken',
            proto_dot_control__plane__pb2.CreateRunnerRegistrationTokenRequest.SerializeToString,
            proto_dot_control__plane__pb2.CreateRunnerRegistrationTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRunnerRegistrationTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/ListRunnerRegistrationTokens',
            proto_dot_control__plane__pb2.ListRunnerRegistrationTokensRequest.SerializeToString,
            proto_dot_control__plane__pb2.ListRunnerRegistrationTokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeRunnerRegistrationToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/RevokeRunnerRegistrationToken',
            proto_dot_control__plane__pb2.RevokeRunnerRegistrationTokenRequest.SerializeToString,
            proto_dot_control__plane__pb2.RevokeRunnerRegistrationTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkflows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/ListWorkflows',
            proto_dot_control__plane__pb2.ListWorkflowsRequest.SerializeToString,
            proto_dot_control__plane__pb2.ListWorkflowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRunners(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.control.v1.ControlPlane/ListRunners',
            proto_dot_control__plane__pb2.ListRunnersRequest.SerializeToString,
            proto_dot_control__plane__pb2.ListRunnersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
