# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import runner_control_pb2 as proto_dot_runner__control__pb2


class RunnerControlStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterRunner = channel.unary_unary(
                '/loop.runner.v1.RunnerControl/RegisterRunner',
                request_serializer=proto_dot_runner__control__pb2.RegisterRunnerRequest.SerializeToString,
                response_deserializer=proto_dot_runner__control__pb2.RegisterRunnerResponse.FromString,
                _registered_method=True)
        self.Connect = channel.stream_stream(
                '/loop.runner.v1.RunnerControl/Connect',
                request_serializer=proto_dot_runner__control__pb2.RunnerToOrchestrator.SerializeToString,
                response_deserializer=proto_dot_runner__control__pb2.OrchestratorToRunner.FromString,
                _registered_method=True)


class RunnerControlServicer:
    """Missing associated documentation comment in .proto file."""

    def RegisterRunner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RunnerControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterRunner': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterRunner,
                    request_deserializer=proto_dot_runner__control__pb2.RegisterRunnerRequest.FromString,
                    response_serializer=proto_dot_runner__control__pb2.RegisterRunnerResponse.SerializeToString,
            ),
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=proto_dot_runner__control__pb2.RunnerToOrchestrator.FromString,
                    response_serializer=proto_dot_runner__control__pb2.OrchestratorToRunner.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loop.runner.v1.RunnerControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loop.runner.v1.RunnerControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RunnerControl:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterRunner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loop.runner.v1.RunnerControl/RegisterRunner',
            proto_dot_runner__control__pb2.RegisterRunnerRequest.SerializeToString,
            proto_dot_runner__control__pb2.RegisterRunnerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/loop.runner.v1.RunnerControl/Connect',
            proto_dot_runner__control__pb2.RunnerToOrchestrator.SerializeToString,
            proto_dot_runner__control__pb2.OrchestratorToRunner.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
