from __future__ import annotations

from typing import Protocol

from .models import Issue, Project


class IssueTracker(Protocol):
    async def list_eligible_issues(self, project: Project) -> list[Issue]: ...
    async def add_labels(self, project: Project, external_issue_id: str, labels: list[str]) -> None: ...
    async def remove_labels(self, project: Project, external_issue_id: str, labels: list[str]) -> None: ...
    async def close_issue(self, project: Project, external_issue_id: str) -> None: ...


class CodeHost(Protocol):
    async def create_or_find_pull_request(self, workflow_id: str, branch: str) -> dict[str, str]: ...
    async def required_checks(self, pull_request_id: str) -> list[dict[str, str]]: ...
    async def merge_pull_request(self, pull_request_id: str, method: str) -> None: ...
